### ISSUE TITLE
Broken link in Co-Ops SOS notebook

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/notebooks_demos#100]
@ocefpaf  - between lines 8 and 9 of  the[ Co-Ops SOS notebook](http://ioos.github.io/notebooks_demos/notebooks/2016-10-12-fetching_data/) the link to the first_difference code doesn't work.

**Comment by ocefpaf** [comment]
What is the error you are getting? I will try it locally in a moment...

**Comment by jbosch-noaa** [comment]
404 :(

**Comment by ocefpaf** [comment]
Got it. Fixing it...

**Comment by jbosch-noaa** [comment]
The collector2table link doesn't work either.

**Comment by jbosch-noaa** [comment]
Yay!  All fixed

**Comment by ocefpaf** [comment]
The problem is that `%20` (space/break character) added during the conversion.
