### ISSUE TITLE
Convert the wiki instructions a page here

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#106]
It feels weird to click on the install instructions and get re-directed to the wiki. We should make that a first class page.

**Comment by jbosch-noaa** [comment]
Yeah but I think the instructions on the Wiki are important because they show folks how to get the IOOS environment.  So to clarify, you are making the Wiki page a regular webpage?

**Comment by ocefpaf** [comment]
> So to clarify, you are making the Wiki page a regular webpage?

Yep. The same info, but with the look and feel of the webpage. Is that OK?

**Comment by jbosch-noaa** [comment]
YES.  That is a great idea.

**Comment by ocefpaf** [comment]
I am playing with the idea of adding that to the top menu instead of the side bar. What do you think?

![webpageioos](https://cloud.githubusercontent.com/assets/950575/20021577/2892aa96-a2b5-11e6-937d-9972f4ff61ec.png)


May we should make the title shorter to match `Gallery` and `About`?

**Comment by jbosch-noaa** [comment]
hummm... 

Jenn's stream on consciousness:
That idea is good because then the left side bar can be exclusively video tutorials ... but I wonder ... does it confuse people when we start posting notebooks in other languages?  Maybe not ... If we put in on the top menu, perhaps we shorten it to just "The IOOS conda environment"

**Comment by ocefpaf** [comment]
>  confuse people when we start posting notebooks in other languages?

We use `conda` mostly for Python but it is actually Python agnostic. We can install [`R`](https://github.com/ocefpaf/2016-Python-course-CBO/blob/master/environment.yml#L41-L42) from the `r` channel. We also will be using the `Jupyter` notebook to call other language kernels installed from `conda` or not.

(BTW the example above is from a [short course](http://nbviewer.jupyter.org/github/ocefpaf/2016-Python-course-CBO/blob/master/notebooks/slides.ipynb) I will be teaching in a [conference](http://www.cbo2016.org/) here next week where I even got [Fortran](https://github.com/ocefpaf/2016-Python-course-CBO/blob/master/appveyor.yml#L23) on Windows working with conda!)

**Comment by jbosch-noaa** [comment]
Nice!  Ok.  Lets do it and just roll with it for now.  If issues come up down the line we can address them.
