### ISSUE TITLE
Shift the order of links across the top to have "About" be the first link

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#112]
cc @jbosch-noaa

**Comment by jbosch-noaa** [comment]
Ok how do we do this?  If I wanted to change this, what do I do?
It seems like a simple thing to do. I am assuming I get in to some code but I don't want to tinker with something I don't fully know about.

**Comment by ocefpaf** [comment]
@jbosch-noaa see https://github.com/ioos/notebooks_demos/pull/120

> > Ok how do we do this? If I wanted to change this, what do I do?
It seems like a simple thing to do. I am assuming I get in to some code but I don't want to tinker with something I don't fully know about.

To be honest, even though the change is simple as you can see in https://github.com/ioos/notebooks_demos/pull/120/commits/4b023d81ecde0140f552cfcabf50d4f2e38ad1cb , I am not 100% familiar with the Jekyll theme yet and it takes some time to find where things are.
