### ISSUE TITLE
Place the post date at the top/title

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#113]
cc @jbosch-noaa

**Comment by ocefpaf** [comment]
@jbosch-noaa the image below is how it would look in our theme right.

![dateontop](https://cloud.githubusercontent.com/assets/950575/20577712/5f0829ba-b1a2-11e6-93af-9dd24925a848.png)

I have to be honest and I really prefer that information in the footer.

PS: Since this is a theme related change I am pinging @mwengren here too to get his opinion.

**Comment by jbosch-noaa** [comment]
I don't mind the date at the top.  It lets folks know how recent the post is. It makes the rendered notebook look more like a blog post that a standalone notebook. What do you think @mwengren ?

**Comment by ocefpaf** [comment]
Here is the date using the footer instead of the header for comparison:

![datebottom](https://cloud.githubusercontent.com/assets/950575/20578357/c1d7451e-b1a5-11e6-99bb-56b42f524503.png)

**Comment by mwengren** [comment]
Looks ok to me.  Will merge.
