### ISSUE TITLE
Problems with IOOS env and Axiom THREDDS Crawler

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/notebooks_demos#12]
@ocefpaf and @rsignell-usgs,
 
So I tried to install the Axiom THREDDS crawler software the other day while I was in the IOOS environment.   https://github.com/asascience-open/thredds_crawler

I started up Python today and my environment.yml file was gone! Launcher tells me "no python is installed" within the IOOS environment.  How did that happen?!

I re-downloaded the environment.yml file but nothing has changed. :(  Short of uninstalling the environment (which I need admin privs to do) I am not sure what my next step should be.

**Comment by ocefpaf** [comment]
Argh! Not sure if the latest updates in conda changed something but I am getting tons of people complaining about that!

Sorry, but I can't say much beyond:

- re-install miniconda
- update with `conda update --all` before doing anything with it
- re-create the ioos environment using https://github.com/ioos/notebooks_demos/wiki/Installing-Conda-Python-with-the-IOOS-environment

Let me know how that goes.

**Comment by jbosch-noaa** [comment]
I haven't re-installed miniconda but I updated with conda update --all and it seemed to have fixed most things.  I then downloaded the environment.yml file and things seem to be fine.

**Comment by ocefpaf** [comment]
Awesome! You were probably hitting the conda-env bug and updating fixed it.
