### ISSUE TITLE
Sidebar Edits

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/notebooks_demos#122]
@ocefpaf  - Here is the file I think we need to edit:  notebooks_demos/webpage/_data/navigation.yml

**Comment by ocefpaf** [comment]
See https://github.com/ioos/notebooks_demos/issues/123 for the demo.

PS: we can add/remove/modify the side bar entries there, but the style can only be changed in the https://github.com/ioos/ioos_jekyll_theme repository.

**Comment by jbosch-noaa** [comment]
Ok.  Here is the section of code we should edit:
https://github.com/ioos/notebooks_demos/blob/master/webpage/_data/navigation.yml#L12

**Comment by ocefpaf** [comment]
OK. Implementing that as soon I finish the conventions notebook. Hold on...

**Comment by ocefpaf** [comment]
@jbosch-noaa let's close this issue since everything we could do here was already done. I will take a look at ioos/ioos_jekyll_theme#24 as soon as possible,
