### ISSUE TITLE
AppVeyor failure

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#129]
Not sure why AppVeyor is failing with 

```shell

[Running notebook]: C:\projects\notebooks-demos\notebooks\2016-11-15-glider_data_example.ipynb
[Failed]
An error occurred while executing the following cell:
------------------
import iris
iris.FUTURE.netcdf_promote = True
glider = iris.load(url)
print(glider)
------------------
OSError: NetCDF: Invalid argument
```

`Linux` and `OS X` can execute that notebook just fine :unamused:

**Comment by ocefpaf** [comment]
@rsignell-usgs I cannot reproduce that with my old Windows XP VM. If you find some time can you test that notebook on your machine? Maybe that endpoint is blocking `AppVeyor`...

**Comment by rsignell-usgs** [comment]
I'm getting that same error when I try to run that notebook on windows.   When I try `ncdump` in my Anaconda prompt, I get:

```
(ioos3) C:\Users\rsignell\Documents\GitHub>ncdump -h "http://data.ioos.us/thredd
s/dodsC/deployments/rutgers/ru29-20150623T1046/ru29-20150623T1046.nc3.nc"
CURL Error: SSL connect error
curl error details:
ncdump: http://data.ioos.us/thredds/dodsC/deployments/rutgers/ru29-20150623T1046
/ru29-20150623T1046.nc3.nc: NetCDF: I/O failure
```

**Comment by ocefpaf** [comment]
That explains why I can access on my old Windows XP VM. Thanks!

I will check what we can do about it but we probably have a bad mix of SSL version in conda-forge.

**Comment by rsignell-usgs** [comment]
I try to open in netCDF-Java on windows, I get this:
![2016-11-21_9-50-42](https://cloud.githubusercontent.com/assets/1872600/20487083/185fa188-afd0-11e6-9be2-6f91453bcbc5.png)

That doesn't depend on any python!

**Comment by ocefpaf** [comment]
> That doesn't depend on any python!

I know, it is the openssl version used like I mentioned above. Ee can use a more permissive openssl version. I am investigating that... Although I am not sure it is recommended. The error is there for a reason.

**Comment by ocefpaf** [comment]
It is not something that we can fix. I am trying a few workarounds though, but they may not be recommended. Stay tuned...

**Comment by ocefpaf** [comment]
This is fixed via a patch and the next `netcdf` lib will fix this for good.
