### ISSUE TITLE
Discuss how to link to external publication

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#131]
@dpsnowden said:

> Do we also have a plan to catalog and link to other things we learn about through various associations?  I just heard about a few examples the OBIS crew is thinking about or is currently writing.  Can we just link to theirs when they publish?

**Comment by jbosch-noaa** [comment]
Here are a few external notebooks and posts we would like to call our reader's attention to: 

@lukecampbell ’s notebook on finding a glider deployment
https://gist.github.com/lukecampbell/8c47b3b110a1ed6f08d7cf658d71008e

QARTOD Notebook set-up - also written by Luke
https://ioos.github.io/qartod/examples/QARTOD%20Examples.html#notebook-setup

R:
OBIS Tutorial - Interacting with OBIS data using R
http://iobis.org/tutorial/

**Comment by ocefpaf** [comment]
@jbosch-noaa everything that is a notebook we can ask for permission and incorporate in the blog.
(@lukecampbell can we do that for https://gist.github.com/lukecampbell/8c47b3b110a1ed6f08d7cf658d71008e BTW?)

We also chose to remove the other resources as a section and decided to place it as an item in the side bar. That can be a page with all these links. What do you think?

**Comment by lukecampbell** [comment]
Yeah, that's fine! We want people to know about the GliderDAC interfaces and how you can integrate them into a good workflow.

**Comment by jbosch-noaa** [comment]
@ocefpaf  - I agree with your suggestions.  

@lukecampbell  - Would you mind beefing up the comments on your notebook?  Just a little at the top explaining what you are going to do and why.  This is just so new folks can put the notebook in context.

**Comment by ocefpaf** [comment]
> @lukecampbell - Would you mind beefing up the comments on your notebook? Just a little at the top explaining what you are going to do and why. This is just so new folks can put the notebook in context.

@jbosch-noaa I am re-writing the notebook and expanding it a little bit. There is no for @lukecampbell to do anything right now. (But I will bother him for a quick review later :wink:)

**Comment by ocefpaf** [comment]
This discussion can be closed as we agreed on how to link external resources.
