### ISSUE TITLE
Add a "How to contribute" section

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#132]
The workflow to check for notebook quality, execution errors, and publication is all automated so we can start advertising this.

**Comment by jbosch-noaa** [comment]
We should put a "contact us" email : data.ioos@noaa.gov in either the side bar or at the top

**Comment by jbosch-noaa** [comment]
@ocefpaf  - Does this answer your "Contact Us" question in PR #147 ?

**Comment by ocefpaf** [comment]
A whole page with an e-mail looks like an overkill. I will put together a small paragraph tomorrow.

**Comment by jbosch-noaa** [comment]
Noooooo.  We don't need a whole page for an email.  Just a quick link to our email. :)

**Comment by ocefpaf** [comment]
> Noooooo. We don't need a whole page for an email. Just a quick link to our email. :)

A section like that is a page :smile: 

We can either add something to the footer with the e-mail or we should write a small paragraph with a quick and simple note.

**Comment by ocefpaf** [comment]
As we discussed today the `Contact us` will be in the landing page, that is a modified version of our current `About` page. But do we still want a `How to contribute` section? I am inclined to say no as it will entail teaching the GitHub workflow `fork` &rarr; `branch` &rarr; `PR` and teaching the Jupyter notebook workflow. Those who have notebooks usually already know how to the the `former`, and if not they can just open an issue with the file and someone else can prepare the PR.

What do you say  @jbosch-noaa?

**Comment by jbosch-noaa** [comment]
I agree.  We don't need a "How to contribute section" because it says on the landing page that if folks are interested in contributing they should contact us.
