### ISSUE TITLE
Blog Name Change

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/notebooks_demos#133]
To folks outside the programming world a "Notebook" is like a diary or a journal.  A "Gallery" is where they expect pictures.  I think we should change the name...  suggestions welcome

**Comment by ocefpaf** [comment]
The reason why the IPythonn guys chose the `IPython notebook` name (now `Jupyter notebook`) is so people can relate to a diary or a journal. ([Here](https://github.com/jupyter/design/wiki/Jupyter-Logo#where-does-the-name-come-from) is the reference that explains the modern name and Galileo's [notebook](https://www.authorea.com/users/3/articles/6316/_show_article) that started it all.)

Regarding gallery... Well... We do expect nice pictures in all notebook too :smile: 

Not sure we need a name change but @rsignell-usgs and @kwilcox are gifted when it comes to naming stuff.

**Comment by jbosch-noaa** [comment]
The problem is that not everyone using this site will be a python programmer.  Also, this site is a place where people can see more than notebooks.  They can find links to video tutorials also.

Ideas from the program office include:
The IOOS ...
Data Access Emporium
Data Usage Farm
Data Demo Blog
Data Demo Hub
Data Knowledge Hub
Data Knowledge Exchange

**Comment by ocefpaf** [comment]
> The problem is that not everyone using this site will be a python programmer.

But notebooks are not Python only. The name Jupyter itself is a combination of `Julia`, `Python`, `R`. But today the [list](https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages) of kernels is way more than that.


> Data Access Emporium
Data Usage Farm
Data Demo Blog
Data Demo Hub
Data Knowledge Hub
Data Knowledge Exchange

any of those look good to me. But I think `Data Demo Blog` may be more appropriated.

**Comment by jbosch-noaa** [comment]
Our new blog name is "The IOOS Data Demo Center"  This should be at the top of our blog, perhaps in the blue section?

Also across the blue section should be the headings:
About
Code Gallery
IOOS Tutorials
Python Tools
Other Resources

Under Python Links we can add Rich's video talks and Emilio's tutorial links
Under "Other Resources" we can link the "How to Install the IOOS Environment" 
We can add more as we discover them.

**Comment by ocefpaf** [comment]
@jbosch-noaa where should the `Installing the IOOS conda environment` go? Should I remove it or leave it as is?

**Comment by jbosch-noaa** [comment]
Start a new section called "Other Resources"

**Comment by ocefpaf** [comment]
> Under "Other Resources" we can link the "How to Install the IOOS Environment"

I guess my question was ill formed. Should I start that section and add only a link or should I make the new section the "How to Install the IOOS Environment" page?

**Comment by ocefpaf** [comment]
> Under Python Links we can add Rich's video talks and Emilio's tutorial links

By `Python Links` you mean the `Python Tools` section, correct? Just to be sure. I am preparing that PR now.

BTW it is not clear to me yet. Do you want me to remove those links from the side-bar and add them in the `Python Tools` section?

**Comment by ocefpaf** [comment]
Done in #147 and #148
