### ISSUE TITLE
How to submit data to NCEI using bagit in python

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/notebooks_demos#134]
@mbiddle-nodc said he would like to see if we can make a notebook about using bagit (https://github.com/LibraryOfCongress/bagit-python) to create submission packages for NCEI. 

I think this is a great idea!

**Comment by ocefpaf** [comment]
@kwilcox is packaging it now. We can do that as soon as the package is in the channel.

See https://github.com/conda-forge/staged-recipes/pull/1983

**Comment by kwilcox** [comment]
Hmmmm... I wonder why I'm packaging it....

I can share the python code that is generating the bagit packages for NCEI when the process is all setup and ironed out.

**Comment by jbosch-noaa** [comment]
That's cool @kwilcox.  @mbiddle-nodc mentioned he would like to refine his notebook authoring skills so you can pass it on to him and he can make the notebook pretty.

**Comment by jbosch-noaa** [comment]
Hey @kwilcox and @mbiddle-bcodmo  - I just received interest from @aaron-sweeney about this project. He is interested in moving this notebook idea forward. Were are the two of you on this project?  

Matt - do you have any starter code Aaron could work with? 

Kyle - do you have any code?  

I would love to see a notebook demonstrating how to submit data to NCEI using python and bagit.

**Comment by mbiddle-bcodmo** [comment]
The thought was the code @kwilcox wrote would be leveraged for this effort. Use that as a base to write a notebook that shows a living example of generating an archive package using python and BagIt which NCEI then archives.

**Comment by kwilcox** [comment]
If somoene writes a notebook that saves a collection of netCDF files to disk then I'll add the code cells to create the bagit archive!

**Comment by mbiddle-bcodmo** [comment]
@fgayanilo started something here https://github.com/GCOOS/csv2nc.

**Comment by ocefpaf** [comment]
> If someone writes a notebook that saves a collection of netCDF files to disk then I'll add the code cells to create the bagit archive!

I have one that finds glider data from the glider DAC and downloads the netcdf files.
I'll send you a gist soon (or you can send me a gist with of the bagit part. I never used it before)

> @fgayanilo started something here https://github.com/GCOOS/csv2nc

That looks like a tool to convert csv files to nc (maybe we could use `pocean` here?) and could diverge from a simple example demonstrating `bagit`, no?

**Comment by fgayanilo** [comment]
I do not know pocean and not familiar with BagIt. These codes are as generic as possible using CSV files as the input source and can be modified easily for other input formats -- and yes, they can be adapted for notebook application.
