### ISSUE TITLE
Link the notebook repo file to each post

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/notebooks_demos#135]
@ocefpaf  - 
Feedback from @dpsnowden that I think is a great suggestion.  We should put a link to the notebook .ipynb file on the repo at the bottom of the published notebook on the blog so folks can download the  file and run it themselves.

This would of course mean editing the already published notebooks (all 3 of them) and making it a habit to do so with all future notebooks. :)

**Comment by ocefpaf** [comment]
That is relatively easy to do. (We had that in the `system-test` and my personal blog actually. I just forgot to put it here.)

**Comment by ocefpaf** [comment]
@jbosch-noaa I am addressing this by adding a footer in all notebooks with the markdown cell

```markdown
You can [download](https://raw.githubusercontent.com/ioos/notebooks_demos/master/notebooks/2016-10-12-fetching_data.ipynb) this notebook, or see a static view [here](http://nbviewer.ipython.org/urls/raw.githubusercontent.com/ioos/notebooks_demos/master/notebooks/2016-10-12-fetching_data.ipynb).
```

Which will render as:

---

You can [download](https://raw.githubusercontent.com/ioos/notebooks_demos/master/notebooks/2016-10-12-fetching_data.ipynb) this notebook, or see a static view [here](http://nbviewer.ipython.org/urls/raw.githubusercontent.com/ioos/notebooks_demos/master/notebooks/2016-10-12-fetching_data.ipynb).

---

what do you think?

**Comment by jbosch-noaa** [comment]
I like it. :)
