### ISSUE TITLE
Archive Idea

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/notebooks_demos#144]
When we get enough blog posts to start archiving them, I think we should have a sub-page like this one:

https://rsms.me/archive/

**Comment by MathewBiddle** [comment]
@ocefpaf, is this still relevant? Where are the blog posts to be archived?

**Comment by ocefpaf** [comment]
I believe that a form of this is still relevant. We need to:

- mark stale notebooks as deprecated;
- check if JB has a way to archive, hide, or anything that we can control who and how people see them.

The reason to not remove is b/c stable or deprecated notebook still contains pieces of code that are useful even though they may not run.

**Comment by MathewBiddle** [comment]
@lohithmunakala do you know if 
> JB has a way to archive, hide, or anything that we can control who and how people see them.

Forgot about the stale/deprecated notebooks. Yes, I agree keeping some of them for code value is worthwhile. We'll probably just have to add a word of caution at the top of those pages. Do we have a list of them in another ticket?

**Comment by ocefpaf** [comment]
> Do we have a list of them in another ticket?

I do have a list but not in a ticket. I'll create one ASAP.

**Comment by lohithmunakala** [comment]
> @lohithmunakala do you know if
> 
> > JB has a way to archive, hide, or anything that we can control who and how people see them.

@MathewBiddle, I did some research, and there isn't any way we can hide specific notebooks or make them visible to only some people. Although there is an option where we could do would be to able to remove/hide certain contents of the cell in the notebooks, which isn't what we want here as far as I understand.

**Comment by ocefpaf** [comment]
@lohithmunakala we can just move them to an "archived" folder that is not in the JB build path.

**Comment by ocefpaf** [comment]
We are marking stale notebooks and we can "hide" them when the time comes. Let's close this for now.
