### ISSUE TITLE
Enhance the landing page

### ISSUE THREAD

**Issue by dpsnowden** [ioos/notebooks_demos#150]
The main [landing page](https://ioos.github.io/notebooks_demos/) could use some enhancements.  The landing page is strictly text.  Is there a graphic we can use?

**Comment by jbosch-noaa** [comment]
@ocefpaf - What is the appropriate path for images that I put on the video tutorials page and the landing page?

Right now I put a bit of code like this in front of each video section in the video_tutorials.md file but I need a full path: 
<img src="IOOS-logo_little.png"> IOOS

**Comment by jbosch-noaa** [comment]
Plan to add to side bar the following links:

Unidata Jupyter Notebook Gallery
http://unidata.github.io/notebook-gallery/

OBIS Tutorial - Interacting with OBIS data using R
http://iobis.org/tutorial/

Integrated Marine Observing System (IMOS) User Code Library 
https://help.aodn.org.au/aodn-data-tools/user-code-library/

**Comment by ocefpaf** [comment]
@jbosch-noaa just to xref things here: the links are in #166, and the image is in #167

**Comment by jbosch-noaa** [comment]
Most of these issues have been resolved so I'm closing this issue.
