### ISSUE TITLE
Download link for notebook is broken

### ISSUE THREAD

**Issue by dpsnowden** [ioos/notebooks_demos#151]
See the nbviewer link for the glider plotting notebook.  http://nbviewer.jupyter.org/urls/raw.%20githubusercontent.com/ioos/notebooks_demos/master/notebooks/2016-11-15-glider_da%20ta_example.ipynb

**Comment by ocefpaf** [comment]
Somehow nbconvert is breaking all long links to fit a specific text width. (See the last line of https://raw.githubusercontent.com/ioos/notebooks_demos/gh-pages/_notebooks/2016-11-15-glider_data_example.md).

I could shorten that as I did in the past but instead I will investigate a better solution (and permanent) solution.
