### ISSUE TITLE
Add a Matlab notebook

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/notebooks_demos#157]
This is an issue to remind us to identify a matlab example notebook.  I am aware that @mbiddle-nodc has a relevant matlab script or two. A few of the RAs might as well.

**Comment by ocefpaf** [comment]
@rsignell-usgs do you have anything that we could use here? I don't really have anything interesting using matlab :disappointed:

**Comment by ocefpaf** [comment]
We forgot to close this when merging #204
