### ISSUE TITLE
Add a R notebook

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/notebooks_demos#158]
This issue is to remind us to put together an R notebook.

**Comment by jbosch-noaa** [comment]
@robragsdale sent us a link to the USGS R Github site:

https://github.com/USGS-R

There are some useful link and examples there.  Lets put this as another link under the Additional Resources sidebar.

**Comment by ocefpaf** [comment]
> This issue is to remind us to put together an R notebook.

We already have one from https://github.com/ioos/notebooks_demos/pull/180 so maybe we should close this issue.

> @robragsdale sent us a link to the USGS R Github site:
https://github.com/USGS-R
There are some useful link and examples there. Lets put this as another link under the Additional Resources sidebar.

OK. Doing that now!

**Comment by ocefpaf** [comment]
@jbosch-noaa we have one R notebook and I added the link. I am closing this so we can open new issue with specific R-notebooks ideas instead of relying on an old and generic issue.
