### ISSUE TITLE
Don't use the titles in the yaml config

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#16]
Pre-defining the model "titles" is just a trick for the plots and we don't really need that. We can find a better way. (Looking into bokeh plots were I could use the whole title in the metadata.)

Ping @rsignell-usgs

**Comment by rsignell-usgs** [comment]
Good.  Seeing all those URLs in the beginning just hard-wired kills the cool story about catalog-driven workflows, even if they are just being used for titles.

**Comment by ocefpaf** [comment]
I tried many ways to "identify" a model based on the metadata and ended up settling for the dictionary approach above. I will try again some text hacks and, if nothing is found, just use the URL. However, to make a clear graph I need to convert it to bokeh first b/c I believe I will have more "space" to customize it.

**Comment by ocefpaf** [comment]
Done in #28 

PS: Actually I still use a dictionary of known model names and try to guess when that fails. But since that is a "hidden" dict no one will think that we hard-code URLs.
