### ISSUE TITLE
Python & R Notebook

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/notebooks_demos#165]
Write a notebook showing how to access data with Python and then use R to analyze that data.

**Comment by ocefpaf** [comment]
We have Python or R now/ But for Python and `R` and need `rpy2`.

xref: https://github.com/conda-forge/staged-recipes/pull/2309#issuecomment-280846313

**Comment by ocefpaf** [comment]
Thanks to https://github.com/conda-forge/staged-recipes/pull/2950 we can finally do this one!

**Comment by jbosch-noaa** [comment]
Lets get this one moving  ... perhaps do something with nutrients and spring storms?

**Comment by ocefpaf** [comment]
Good idea. I can start it next week (I am at SciPy this week).

**Comment by ocefpaf** [comment]
Notes from today's meeting:

- USGS stream gauges (Nitrogen/Chlorophyll)
- Chesapeake bay / Mississippi 
- Spring (March-May)
