### ISSUE TITLE
"Suggest a Demo" button - aka- how to open a GitHub issue

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/notebooks_demos#175]
We should put a "Suggest a Demo" button on our site. Perhaps in the sidebar.  The button would link to our GitHub repo.  

We can also include a separate link on how to open a GitHub issue.  @ocefpaf mentioned that GitHub has some templates for issues and we can create an example to guide people how to do it.

**Comment by jbosch-noaa** [comment]
@ocefpaf  - What do you think of this icon to put across the top corner of our pages? We can use it to link to our GitHub repo.

![suggestdemo png](https://cloud.githubusercontent.com/assets/13106516/22388218/747e5a06-e4ad-11e6-8c7c-20ccfc9b9bc2.png)

**Comment by ocefpaf** [comment]
That is awesome! Thanks for putting this together @jbosch-noaa. I am looking how to best add that without adding it to the theme, because that is specific to this site.

**Comment by jbosch-noaa** [comment]
@ocefpaf - here is the website I found the icon on.  That might help?

http://tom.preston-werner.com/

**Comment by ocefpaf** [comment]
This is done. Closing...
