### ISSUE TITLE
Add Google Analytics to this site

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/notebooks_demos#190]
We would like to track who is accessing this webpage.  @mwengren thinks adding Google Analytics is possible on github websites. @ocefpaf and I will need to research the details.

**Comment by ocefpaf** [comment]
@jbosch-noaa you need to create an account at https://analytics.google.com/analytics/web/ (or maybe IOOS has one?) and then I can add the GA number on the page.

**Comment by ocefpaf** [comment]
@jbosch-noaa let me know if you got the `GA` number. I don't want to create one under my username. (Maybe IOOS already have one for the other pages that we can use here.)

**Comment by jbosch-noaa** [comment]
Thanks for pinging me.  This issue got stalled.  I will follow up with folks in the office next week about it.

**Comment by MathewBiddle** [comment]
@mwengren do you know if IOOS has a `GA` number so we can set up Google Analytics?

**Comment by mwengren** [comment]
I don't believe so.  We've gotten RPS to configure GA for the ioos.us sites they manage for us (data.ioos.us, eds.ioos.us, etc) and give us access to them through the GA console.  

For all noaa.gov sites, it's required to use the GSA GA plugin, which is a separate code/source file.  I think info on that is available here: https://digital.gov/guides/dap/add-your-site-dap/.  What I don't know is whether you can use this for non .gov sites or not.  If so, we might look at that approach here.

**Comment by MathewBiddle** [comment]
Should we reach out to dap@support.digitalgov.gov to get some help?

**Comment by mwengren** [comment]
Sure, I don't know how the .gov domain requirements work for that program.  I think from a technical perspective, it might be tricky because a lot of the Jekyll templates like this one have a config element for a GA id string, but they probably load the default JS files with that, and not the GSA ones, of course, which are customized and have different URLs.

It may mean that we'd need to use a standard GA id/account, in which case getting RPS to manage it would be better.  Maybe @ocefpaf has thoughts.

**Comment by ocefpaf** [comment]
> Maybe @ocefpaf has thoughts.

Actually, was thinking about experimenting with https://www.goatcounter.com/ to avoid some of Google's problems with ga. What do you think?

**Comment by MathewBiddle** [comment]
I see this as a possible concern with the free instance
> 6 months data retention

Do we have an idea on page views per month?
I assume Google wont have these limitations.

It might be worth exploring if implementation is easier, though. I'll lean on @mwengren for thoughts.

**Comment by fgayanilo** [comment]
I do not know if this discussion is limited to GA applications but I use (and I know a couple of RAs doing the same) a log analyzer like AWStats (https://awstats.sourceforge.io/). GA works only for page visits but not if it is M2M direct access.

**Comment by MathewBiddle** [comment]
@mwengren, I mentioned this to Kate and I think GA is doable here. Where do you recommend we pursue?

**Comment by mwengren** [comment]
Sure, I'll leave it to you guys to decide what route to go.  GA is in use for a lot of our *.ioos.us sites already though.  I guess since this isn't a .gov site, maybe it makes it easier to bypass the DAP GA approach.

**Comment by fgayanilo** [comment]
@MathewBiddle let me know if GA works, most especially with data downloaded or queried from ERDDAP services; if it does, it will be a huge step forward.

**Comment by MathewBiddle** [comment]
@ocefpaf, we've got an ID to configure GA! I'll take a look around the repo to see what needs to be changed to ensure tracking. Expect a PR soon...

**Comment by MathewBiddle** [comment]
Reopening as the analytics aren't connected. We need to do some testing to see what's wrong.

**Comment by MathewBiddle** [comment]
According to the GA instructions, we need to add this into the `<head>` section of HTML. I don't think the jekyll theme is putting it in the right place (or using the right piece). Has this been done before?

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-W7S16LPGS7"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-W7S16LPGS7');
</script>
```

**Comment by MathewBiddle** [comment]
@mwengren 

Looking at [this blog](https://desiredpersona.com/google-analytics-jekyll/), one of the following files should be updated to reflect the code snippet above.

https://github.com/ioos/ioos_jekyll_theme/blob/0eeb408412150d07fd2cb14c2a2e6d2bb3e8cf1d/_includes/analytics-providers/google.html

or

https://github.com/ioos/ioos_jekyll_theme/blob/0eeb408412150d07fd2cb14c2a2e6d2bb3e8cf1d/_includes/analytics-providers/google-universal.html

The snippet would look like:
```
<script async src="https://www.googletagmanager.com/gtag/js?id=G-W7S16LPGS7"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-W7S16LPGS7');
</script>
```

With the code `G-W7S16LPGS7` replaced with `site.analytics.google.tracking_id`. Something like the following (I don't know html/javascript so I'm guessing)

```
<script async src="https://www.googletagmanager.com/gtag/js?id=" + site.analytics.google.tracking_id ></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config',  site.analytics.google.tracking_id );
</script>
```

Then, we need to put something like this (maybe without the `jekyll.environment` part)
```
{% if site.google_analytics and jekyll.environment == 'production' %}
{% include analytics.html %}
{% endif %}
```
in
https://github.com/ioos/ioos_jekyll_theme/blob/0eeb408412150d07fd2cb14c2a2e6d2bb3e8cf1d/_includes/head.html 
or
https://github.com/ioos/ioos_jekyll_theme/blob/0eeb408412150d07fd2cb14c2a2e6d2bb3e8cf1d/_layouts/default.html

**Comment by ocefpaf** [comment]
We'll need to change it again when we address #386. Maybe we should put this one on hold for now and ask the GSoC student to do this for the JB?

**Comment by MathewBiddle** [comment]
closing as #407 is more appropriate.
