### ISSUE TITLE
CSW demo can't be downloaded and run

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/notebooks_demos#192]
The [CSW example notebook](http://ioos.github.io/notebooks_demos/notebooks/2016-12-19-exploring_csw/) has a "download" at the bottom, but if you do that you can't run it, even if you have the IOOS environment, because it depends on 
```
ioos_tools = os.path.join(os.path.pardir)
sys.path.append(ioos_tools)
```

**Comment by ocefpaf** [comment]
I am on the fence about that custom module for a while the options are:

- make it a module and maintain it, like we had before;
- change the instructions to inform users that they can only run by cloning the repo;
- keep the current format and add a caveat note that some notebooks may need some extra steps.

All those have their pros and cons and to be honest I don't like any of them. I'd rather have a robust binder-like service and tell people to run there.

See https://markwoodbridge.com/2017/03/05/jupyter-reproducible-science.html for a study on reproducible jupyter notebooks and similar problems.

**Comment by rsignell-usgs** [comment]
Let's go with the lowest effort route for now:  (2).
