### ISSUE TITLE
OBIS R notebook #1

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/notebooks_demos#197]
I am opening an issue here so we can track the development of this R notebook proposed by @bbest. 

_From the email Ben sent to Roger, Abby, Mitch, and myself:_

Here's a little R code to extract depth data from a raster for OBIS records and map out:

    benbestphd.com/obis-lat-time-fig

I could similarly extract EMU values for the OBIS records. (I would do this by representing the EMU depth bins as a raster stack and then select out the appropriate depth.) We could post this on the IOOS notebook site.

**Comment by ocefpaf** [comment]
Once you have the code let me know the `R` libraries that will be needed so I can start adding/packaging them into our IOOS env.

**Comment by bbest** [comment]
Thanks @jbosch-noaa & @ocefpaf! Just pinged Roger Sayre about access to the EMU data.

**Comment by ocefpaf** [comment]
We have https://github.com/ioos/notebooks_demos/pull/288 but we could use examples :smile:
@jbosch-noaa do want to leave this open?

**Comment by jbosch-noaa** [comment]
Lets leave this open for now and see if @bbest has anything more to contribute.
