### ISSUE TITLE
Revised instructions

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#20]
@jbosch-noaa and I went over the install instructions yesterday again, and I updated the wiki with our findings:

https://github.com/ioos/notebooks_demos/wiki/Installing-Conda-Python-with-the-IOOS-environment

Mostly we want the "most common" installation to be clearer and writing the "exceptions" as side notes.
I also moved the environment file to this repository to make it easier to manage and added a few extra packages for a smoother experience.

One alternative is to use `conda constructor` to create a simple installer. The main advantage is a single download and install.The main disadvantage is adding another Python distribution, derived from `miniconda` BTW, into the mix.

If someone is feeling adventurous and want to try this route:

[`Linux`](https://dl.dropboxusercontent.com/u/4411725/ioos-1.0-Linux-x86_64.sh), [`OS X`](https://dl.dropboxusercontent.com/u/4411725/ioos-1.0-MacOSX-x86_64.sh), [`Windows 32`](https://dl.dropboxusercontent.com/u/4411725/ioos-1.0-Windows-x86.exe), and [`Windows 64`](https://dl.dropboxusercontent.com/u/4411725/ioos-1.0-Windows-x86_64.exe).

Bare in mind that this **is** experimental!

**Comment by rsignell-usgs** [comment]
I clicked the `Windows 64

**Comment by ocefpaf** [comment]
Updating the link soon. (I don't have anything better than a Public Dropbox folder for now.)

**Comment by ocefpaf** [comment]
Uploaded to Dropbox completed! I tested the `Linux` installer that that worked perfectly. The Windows 32 issued an error while creating the menu entries, but after a manual activation things "work" if you are comfortable with the CLI.

![constructor_error](https://cloud.githubusercontent.com/assets/950575/17552825/aa81f122-5ed8-11e6-9785-5859e149d4b4.png)

I could not test Windows 64 nor OS X.

**Comment by lukecampbell** [comment]
I can verify the OS X instructions next week.

**Comment by ocefpaf** [comment]
> I can verify the OS X instructions next week.

Thanks @lukecampbell!

**Comment by lukecampbell** [comment]
They work, no issues. Word of caution though don't cat the install bash script. I don't like downloading and running scripts from untrusted sources (my trusted sources include only me). So I wanted to inspect it for potentially malicious code. 99% of that huge "bash script" is a BLOB.

**Comment by ocefpaf** [comment]
Thanks @lukecampbell!

That blob is "ugly" but it is the only output of conda-constructor so far.
