### ISSUE TITLE
Glider Data

### ISSUE THREAD

**Issue by lukecampbell** [ioos/notebooks_demos#207]
Regarding the glider data example, https://ioos.github.io/notebooks_demos/notebooks/2016-11-15-glider_data_example/

I just wanted to point out that I have a rather thorough algorithm for plotting glider data from GliderDAC. The problem with standard glider data is that it suffers from:
 - Out of order
 - Profiles that aren't strictly monotonically increasing or decreasing depth
 - NaNs everywhere
 - Spikes and incredibly large/small values (erroneously)

I wrote a plotting algorithm that smooths out the data and overcomes many of the limitations of glider data that isn't strictly quality controlled.

It might be worthwhile to link to this if anyone wants to take on the challenge of plotting glider data too.

https://github.com/ioos/glider-dac-status/blob/master/status/profile_plots.py

**Comment by jbosch-noaa** [comment]
I'm just catching up on these open issues.  Thanks @lukecampbell .  That's a great idea. 

@ocefpaf - I think we should make an edit to the notebook and point folks to Luke's python script for more information.

**Comment by ocefpaf** [comment]
Will do.
