### ISSUE TITLE
Create an R Notebook to align data to Darwin Core

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/notebooks_demos#248]
This is a GitHub issue to track my converting Abby Benson's R script to align data to Darwin Core for submission to OBIS.

**Comment by ocefpaf** [comment]
> Abby Benson's R script to align data to Darwin Core for submission to OBIS.

@jbosch-noaa do you have that script online somewhere?

**Comment by jbosch-noaa** [comment]
@ocefpaf - No. I have it in an email I just forwarded to you.

**Comment by MathewBiddle** [comment]
See [Abby's R script](https://github.com/ioos/bio_data_guide/tree/master/Standardizing%20Marine%20Biological%20Data/datasets/example_script_with_fake_data). I made a [Python version](https://github.com/ioos/bio_data_guide/pull/40) and am waiting for it to get merged.

**Comment by MathewBiddle** [comment]
Python notebook is available [here](https://github.com/ioos/bio_data_guide/blob/master/Standardizing%20Marine%20Biological%20Data/datasets/example_script_with_fake_data/IOOS%20DMAC%20DataToDwC_Notebook_event.ipynb). It needs more context if we would like to add it to here.

**Comment by ocefpaf** [comment]
> Python notebook is available [here](https://github.com/ioos/bio_data_guide/blob/master/Standardizing%20Marine%20Biological%20Data/datasets/example_script_with_fake_data/IOOS%20DMAC%20DataToDwC_Notebook_event.ipynb). It needs more context if we would like to add it to here.

Do you want to send a draft PR or should I? We can work on the text/context later.

**Comment by MathewBiddle** [comment]
I can. It'll be good to freshen up my git skills.

**Comment by MathewBiddle** [comment]
Do we still want an R version of this, or does the python version suffice?

**Comment by albenson-usgs** [comment]
An R version [already exists](https://github.com/ioos/bio_data_guide/blob/master/Standardizing%20Marine%20Biological%20Data/datasets/example_script_with_fake_data/IOOS_DMAC_DataToDwC_Notebook_event.md) seems like it wouldn't be that hard to have both so people can use the language they are more familiar with. Would be great if there was some way to display it in the Code Gallery side by side so people could select the one most appropriate to them. Maybe that's a feature beyond the Code Gallery's functionality though.

**Comment by MathewBiddle** [comment]
We do have that R version linked at the bottom of this notebook. 
![image](https://user-images.githubusercontent.com/8480023/109508659-14ddbf00-7a6e-11eb-9e1a-2f7792eb1b02.png)
But, I'm curious what @ocefpaf thinks about hosting two notebooks that accomplish the same task in different languages. I've seen tools at data repositories that auto build code in different languages to ingest data. I'll look around and see if I can find links.

**Comment by albenson-usgs** [comment]
In that case, maybe we should move it to the top of the notebook so that people who would prefer an R version can skip off to that if Python is not their preferred language? I would be frustrated if I had to read through the entire thing to find out there is an example in my preferred language. Also could we link to the [.md](https://github.com/ioos/bio_data_guide/blob/master/Standardizing%20Marine%20Biological%20Data/datasets/example_script_with_fake_data/IOOS_DMAC_DataToDwC_Notebook_event.md) instead of the .R for it?

**Comment by MathewBiddle** [comment]
I moved the reference and linked to the .md. Better?

https://nbviewer.jupyter.org/github/MathewBiddle/notebooks_demos/blob/dwc_fixes/notebooks/2020-12-08-DataToDwC.ipynb

**Comment by MathewBiddle** [comment]
Also, from Stace. Update the language to state **Extended MeasurementOrFact**.

>One quick edit: it appears to me that you are doing an Extended MeasurementOrFact table, which includes the identifiers from controlled vocabularies. https://tools.gbif.org/dwca-validator/extension.do?id=http://rs.iobis.org/obis/terms/ExtendedMeasurementOrFact

**Comment by albenson-usgs** [comment]
Stace is right. We should add the IDs in. I was being lazy (and still struggling with how to find things in the NVS) when I first made the R notebook.

**Comment by MathewBiddle** [comment]
Ahh, I saw the `measurementTypeID` and thought that was `measurementID`... If I understand [this](https://dwc.tdwg.org/list/#dwc_measurementID) correctly, each mof observation needs to have a unique identifier. So, would it be sufficient to add a uuid `uuid.uuid4()` for each row in the measurementorfact dataFrame?

**Comment by MathewBiddle** [comment]
From Stace Beaulieu:
> the distinction is that the 'regular' MeasurementOrFact table does not accommodate identifiers for the Type, Value, Unit (https://tools.gbif.org/dwca-validator/extension.do?id=dwc:MeasurementOrFact), while the Extended MeasurementOrFact table does. I am seeing measurementTypeID and measurementUnitID in your notebook.

**Comment by MathewBiddle** [comment]
The text should be more clear now: https://nbviewer.jupyter.org/github/MathewBiddle/notebooks_demos/blob/dwc_fixes/notebooks/2020-12-08-DataToDwC.ipynb
