### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#263]
@rsignell-usgs it is getting harder and harder to maintain Python 2 and 3 code compliance in the notebooks and packages here. What do you think about finally dropping Python 2.7?

In a way this repository, as a source for code examples, should be using the latest stable version :wink:

**Comment by rsignell-usgs** [comment]
I vote drop python 2.  Let's help folks get on a more forward looking path.

-Rich
