### ISSUE TITLE
FVCOM Unstructured Grid Visualization

### ISSUE THREAD

**Issue by jcdonovan** [ioos/notebooks_demos#285]
Hello,

I have been trying to find examples of open source visualization code for FVCOM model output. I have seen examples in the past written in Python and Matlab. Many of the web sites that I have found in the past no longer seem to be available.

I am able to find a couple useful examples like:

http://nbviewer.jupyter.org/github/rsignell-usgs/ipython-notebooks/blob/master/files/FVCOM_depth_and_velocity.ipynb
https://wiki.fvcom.pml.ac.uk/doku.php?id=tools:post_processing

As someone new to this topic, perhaps I am just not using the correct keywords to find everything that is available. I also remember seeing examples written Python showing a visualization example with ArcGIS as well. That is one I can no longer find. 

I also found a slideshow online that contains descriptions of the type of things I would like to see collected in a notebook demo:

https://www.ioos.noaa.gov/wp-content/uploads/2016/04/Framework-for-Analyzing-and-Visualizing-Met-Ocean-Data_RSignell_Day2.pdf

I cannot find any further discussion of the contents of this slideshow online. Slides on pages 12, 13 and 15 are of particular interest.

It would be very helpful if these FVCOM Visualization examples could be collected in the Code Gallery similar to what is available for the visualization  of Glider data.

Thank you for any help you can provide with this request,
Jeff Donovan

**Comment by rsignell-usgs** [comment]
@jcdonovan , try googling on "nctoolbox" and "dap2arc"

**Comment by ocefpaf** [comment]
>  I have seen examples in the past written in Python and Matlab. Many of the web sites that I have found in the past no longer seem to be available.

I know of two Python libraries for FVCOM:  [PyFVCOM](https://github.com/pwcazenave/PyFVCOM) and [PySeidon](https://github.com/GrumpyNounours/PySeidon) but I am not an FVCOM user and I do not know the maturity not usefulness of those libraries.

> I cannot find any further discussion of the contents of this slideshow online. Slides on pages 12, 13 and 15 are of particular interest.

Right now I know that we can plot horizontal layers, computed horizontal z-slices, and find nearest points easily. We also can, with some difficulty, compute vertical slices and virtual glider paths. These last two are not well developed nor general enough be shipped as a library. (Things may change soon with the YT project that aims to do exactly that.)

> It would be very helpful if these FVCOM Visualization examples could be collected in the Code Gallery similar to what is available for the visualization of Glider data.

We do have a few example like that in notebooks that we could put together in a post here. What do you think @jbosch-noaa? (Right now the only post that mentions unstructured grid is [this one](http://ioos.github.io/notebooks_demos/notebooks/2016-11-16-CF-UGRID-SGRID-conventions/).)

Some examples that might be of your interest:

- http://nbviewer.jupyter.org/github/ioos/ciso/blob/master/notebooks/ciso_FVCOM_example.ipynb
- http://nbviewer.jupyter.org/gist/ocefpaf/69e07c4aa085d33beb8b6011fd6ae9ac

**Comment by ocefpaf** [comment]
We have some example on how to read FVCOM data and how to use UGRID.

Closing this but we will definitely add more examples in the future.
