### ISSUE TITLE
Adapt the unidata blogging system

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#3]
Unidata blog:

https://www.unidata.ucar.edu/blogs/developer/

> Unidata's blog software (Apache Roller) has a plugin that allows it to render source content in Markdown format as HTML.

That part is OK as we do virtually the same. We need adapt the details of the markdown syntax (easy) and the CSS  look and feel (hard).

> Code sections, in particular, are wrapped in HTML `<pre>` and `<code>` tags, which are required for a piece of Javascript called prism.js; this in turn handles the code highlighting on the fly.

https://github.com/unidata/blog-notebooks

- blog-post.py - Nbconvert configuration file, whose main purpose in life is to allow changing the path to the images extracted from the notebook. This makes it so the markdown conversion already points to where the images will be on the server when I upload them separately. (Since I need this step, I also let the config specify the conversion template.)

- blog.tpl - Nbconvert template that tweaks the markdown output. Using this, we can wrap the code in the necessary `<pre>` and `<code>` tags and also do some HTML escaping. More importantly, this template eliminates some of the default output so that things like warnings don't appear in the blog post.

**Comment by dpsnowden** [comment]
I think I might have been the source of this issue.  Just to be clear, I'm not necessarily partial to the Unidata blogging system over any other system.  I'm just asking for a solution to render notebooks into HTML that can be deployed on the intended web site (either, ioos.us or ioos.noaa.gov depending).

**Comment by ocefpaf** [comment]
> I think I might have been the source of this issue. 

I am still looking for an elegant solution for this.

> I'm not necessarily partial to the Unidata blogging system over any other system. 

Agreed. Currently we have pelican but adapting that to make the pages look like the rest of the IOOS pages is not a viable solution due to the high complexity of the theme and notebook conversion there. (They are intertwined and require changes in an unreadable machine generated css template.)

I had the chance to talk with @dopplershift at SciPy 2016 and he mention that they use `nbconvert` directly, with a custom template, and then feed the resulting markdown to `roller`. He also mentioned that `roller` is the tool of choice for Unidata blogs but not an ideal one.

We already have the converter and the template here in the `gh-pages branch`. However, I believe that adapting `jekyll` for the markdown is probably the most robust way. (Not to mention we can automate the page generation "for free" with GitHub when adding a new notebook.)

@jbosch-noaa, @lukecampbell, and I had a meeting some time ago when @lukecampbell mentioned he was preparing a `jekyll` theme that looked like the IOOS pages. If we have that then we are good to start. I am gave `jekyll` a try and here is a few pics:

![front](https://cloud.githubusercontent.com/assets/950575/17931945/13073570-69e4-11e6-8012-f610b62e72f3.png)

![bottom](https://cloud.githubusercontent.com/assets/950575/17931965/2aeab8f6-69e4-11e6-94ae-f2a34837bc20.png)

Warning!!! I am not a HTML/CSS expert and the page is far from OK. @lukecampbell any input here is welcomed!

**Comment by lukecampbell** [comment]
That looks good to me. I still need to apply the same CSS from ioos.us to here at some point. 

Some references:
- https://github.com/ioos/catalog-harvest-registry/blob/master/app/imports/ui/layouts/master-layout.less
- https://github.com/ioos/catalog-harvest-registry/blob/master/app/imports/ui/pages/banner.less

That's the overall layout stylesheet and the banner stylesheet for the blue navbar featured on the modern ioos.us sites.

**Comment by ocefpaf** [comment]
Thanks @lukecampbell I don't really do `css` and the `less` format is even more obscure to me. But I will take a look. Let's move the discussion to #2 as that seems to be the approach we will be taking.
