### ISSUE TITLE
r-obistools missing

### ISSUE THREAD

**Issue by mmartini-usgs** [ioos/notebooks_demos#306]
I am encountering the error below when trying to re-install conda.
This is a show stopper - it won't install the IOOS3 environment because of this error.

```
(base) C:\Users\mmartini\Downloads\anaconda>conda update --yes --all
Solving environment: done

# All requested packages already installed.

(base) C:\Users\mmartini\Downloads\anaconda>conda env create --quiet --file environment.yml
Solving environment: ...working... failed

ResolvePackageNotFound:
  - r-obistools

```

**Comment by ocefpaf** [comment]
I'm assuming you are on Windows.
Unfortunately we do not package `r-obistools` on Windows b/c of its dependency on `r-rgdal`.

(See https://github.com/conda-forge/r-rgdal-feedstock/pull/8 for the details.)

You can use in the `IOOS` environment by installing `obistools` manually in that environment with the commands:

```R
install.packages("devtools")
devtools::install_github("iobis/obistools")
```

from inside an `R` session.

(Just be sure to call the `R` from the IOOS environment and not the system or another installation. You can check that with the `where R` and inspect if the path to the executable.)

**Comment by rsignell-usgs** [comment]
@ocefpaf , perhaps given the R issues, we should have the preferred environment "IOOS" and an alternate "IOOS-lite" without R?

**Comment by ocefpaf** [comment]
I'm all for a light weight IOOS env. We just need to make the docs very clear to avoid confusion.
Most users are using the IOOS env as their every-day "python distribution," even though we never designed it to be that!
