### ISSUE TITLE
R example for NERRS

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#318]
Emilio suggested an `R` example that read NERRS.

**Comment by MathewBiddle** [comment]
Not sure if this is still something of interest. My wife mentioned [this package](https://cran.r-project.org/web/packages/SWMPr/index.html).

[This](https://swmprats.net/all-about-swmpr) might be of interest if we'd like to pursue an activity like this. 

If there's no interest, lets close this ticket.

**Comment by ocefpaf** [comment]
Let's close it for now. We can re-open/open a new one if people are still interested on this.
