### ISSUE TITLE
Port notebooks from the DMAC webinar to the IOOS Data Demo Center

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#334]
[Port the notebooks](https://github.com/ocefpaf/2018-10-25-DMAC-TechWebinar/tree/master/notebooks):

- [X] 00-SOS.ipynb (Done in #330)
- [ ] 01-ERDDAP.ipynb
- [ ] 02-CSW.ipynb
- [ ] 03-PyOOS.ipynb

**Comment by MathewBiddle** [comment]
@ocepaf, do we still want to pull these notebooks over?

**Comment by ocefpaf** [comment]
> @ocepaf, do we still want to pull these notebooks over?

Not sure. It is up to you if this is still relevant. IMO we can have examples today and we should focus on those, like the hurricane animation that uses some of those tech.

**Comment by MathewBiddle** [comment]
Right. I was thinking that those examples are already in some of the notebooks/PRs we have. I'm going with let's move forward and keep working on merging the existing PRs.
