### ISSUE TITLE
Intake catalog of IOOS models, visualized with xrviz

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/notebooks_demos#341]
It would be cool to have an intake catalog of IOOS model output that could be dropped into the [new xrviz tool](https://github.com/intake/xrviz) being developed during [the Google Summer of Code project by @hdsingh](https://github.com/intake/intake-gsoc-gui/blob/master/Report%20for%20GSOC%202019.md)

**Comment by MathewBiddle** [comment]
@rsignell-usgs @ocefpaf, is this still worth pursuing?

**Comment by ocefpaf** [comment]
We started that by trying to figure out how many IOOS models we could get with the catalog but we hit so many catalog issues that this was abandoned. Maybe we should try again.

**Comment by MathewBiddle** [comment]
Gotcha. I'll be meeting Tracy (Coastal Modeling Portfolio Manager) in a few weeks to chat about similar topics. I'll put my notes in a ticket in the code_lab repo.

**Comment by MathewBiddle** [comment]
moved to code lab. closing.
