### ISSUE TITLE
Add RA models

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#348]
In the previous notebooks we did not include 

https://pm2.blob.core.windows.net/f20200106/ocean_surface.nc

There is no THREDDS server for it yet though.

(From e-mail communication.)

**Comment by MathewBiddle** [comment]
@ocefpaf not sure where this stands.

**Comment by ocefpaf** [comment]
Since we cannot find that model via the catalog I'm inclined to close this issue.
