### ISSUE TITLE
New GTS counts graphic (notebook...?)

### ISSUE THREAD

**Issue by kbailey-noaa** [ioos/notebooks_demos#351]
For @ocefpaf 
I'm not actually sure if a notebook is what I'm looking for, but figured you could advise:
The goal is to embed a new graphic in one of our ioos.noaa.gov webpages - probably [here](https://ioos.noaa.gov/data/contribute-data/provision-data-gts/) - that shows volume of IOOS data delivered to the GTS per month.  The graphic would automatically update monthly.

We have statistics (.csv files generated monthly) gathered by NDBC [here](http://www.ndbc.noaa.gov/ioosstats/) that Kevin O'Brien has already put into an ERDDAP here:
https://ferret.pmel.noaa.gov/generic/erddap/tabledap/ioos_obs_counts.html
He downloaded files from Jan 2019 forward.  You can search on platform ID, or sponsor or region.  He also provided me the configuration file in case we want to set up the ERDDAP elsewhere.

I'm looking for a simple bar graph that shows total # obs per month going to the GTS:
![GTSflow](https://user-images.githubusercontent.com/11823385/79789671-9033f780-8318-11ea-8031-cd016a807593.png)

The # obs is a grand total of all stations, wave + met obs.

**Comment by ocefpaf** [comment]
I'll write something as a notebook that we can use to update the page later. Figuring out how to automate this is the trick part though.

**Comment by kbailey-noaa** [comment]
@ocefpaf I've asked @MathewBiddle to help with this since I've been a bit overwhelmed lately.  Matt joined on Monday and part of his duties include metrics/outreach related to our products, so this fits in well.  Matt - See the pull request for the preview.  We can discuss in more detail outside of github. 
Source files are here: https://www.ndbc.noaa.gov/ioosstats/
and the ERDDAP Kevin O stood up is here: https://ferret.pmel.noaa.gov/generic/erddap/tabledap/ioos_obs_counts.html
Met = winds, air pressure, air temp, dew point, water temp
Wave = wave height and dominant wave period
IOOS-regional = RAs plus their affiliates or parters (regardless of funding relationship) as accounted for on the [NDBC website](https://www.ndbc.noaa.gov/to_station.shtml)
Filipe - Is this issue supposed to be closed/replaced with the pull request? Unclear if I should've added this comment to the pull request instead.

**Comment by ocefpaf** [comment]
> @ocefpaf I've asked @MathewBiddle to help with this since I've been a bit overwhelmed lately. Matt joined on Monday and part of his duties include metrics/outreach related to our products, so this fits in well. Matt - See the pull request for the preview. We can discuss in more detail outside of github.
> Source files are here: [ndbc.noaa.gov/ioosstats](https://www.ndbc.noaa.gov/ioosstats/)
> and the ERDDAP Kevin O stood up is here: [ferret.pmel.noaa.gov/generic/erddap/tabledap/ioos_obs_counts.html](https://ferret.pmel.noaa.gov/generic/erddap/tabledap/ioos_obs_counts.html)
> Met = winds, air pressure, air temp, dew point, water temp
> Wave = wave height and dominant wave period
> IOOS-regional = RAs plus their affiliates or parters (regardless of funding relationship) as accounted for on the [NDBC website](https://www.ndbc.noaa.gov/to_station.shtml)

OK. I'll follow up with @MathewBiddle.

> Filipe - Is this issue supposed to be closed/replaced with the pull request? Unclear if I should've added this comment to the pull request instead.


It will be closed when the pull request is merge. Let me just add a few more things to the notebook and we can discuss it with Matt to see how we are going to use this.
