### ISSUE TITLE
Refresh siphon's example...

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#352]
... and create a new one with the new functionalities.

**Comment by emiliom** [comment]
FYI, I recently benefited from the IOOS Data Demo siphon notebook. I could not find better demonstrations or documentations of catalog_ref navigation in the siphon repo, web site or related materials! I've been meaning to add an issue to the siphon repo to suggest to them to add the IOOS siphon notebook to [their Siphon Examples page](https://unidata.github.io/siphon/latest/examples/index.html) ...

**Comment by MathewBiddle** [comment]
Good to know @emiliom! Thanks for taking the time to make a note of the benefits of this notebook.

**Comment by MathewBiddle** [comment]
moved to code lab. closing.
