### ISSUE TITLE
Consider using Pangeo gallery approach?

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/notebooks_demos#357]
I have been contributing Notebook content to the [Pangeo Gallery](https://gallery.pangeo.io), and I like the fact that I can maintain [my own repo](https://github.com/rsignell-usgs/esip-gallery) yet it gets included in the overall gallery.    The notebooks get run by binderbot and the resulting rendered HTML notebook is made available as well as a binder link.   This is all accomplished with github actions.

**Comment by ocefpaf** [comment]
> I have been contributing Notebook content to the [Pangeo Gallery](https://gallery.pangeo.io), and I like the fact that I can maintain [my own repo](https://github.com/rsignell-usgs/esip-gallery) yet it gets included in the overall gallery. The notebooks get run by binderbot and the resulting rendered HTML notebook is made avaialable as well as a binder link. This is all accomplished with github actions.


@rsignell-usgs some of our notebooks cannot be run on the cloud, they need to be built from a notebook with the outputs. The reasons vary, from passwords to access servers to long running data queries. Do you know if that gallery has an option to not run the notebook? Just use it "as-is"?

**Comment by rsignell-usgs** [comment]
Hmm, I do not know.   I can ask.   Or do you want to ask?

**Comment by ocefpaf** [comment]
> Hmm, I do not know. I can ask. Or do you want to ask?

It depends. Who wants to be lectured on how this is a bad idea and does not fit the Pangeo binderhub model :stuck_out_tongue_winking_eye:

**Comment by rsignell-usgs** [comment]
Oh, pick me!   👅

**Comment by ocefpaf** [comment]
Sure. I've done that already. Hopefully you will get a different answer.

**Comment by MathewBiddle** [comment]
Just thinking out loud here. Is this a way we could establish a notebook gallery for each regional association? So, we could have an IOOS Gallery which points to RA repositories? For example, [CenCOOS notebooks](https://github.com/CeNCOOS/notebooks), or something in [NANOOS](https://github.com/nanoos-pnw), or [GCOOS](https://github.com/GCOOS). As well as a repository for the IOOS Data Demo center where we have the examples that have already been developed. 

I like that each group can maintain their own repo and it gets included in the overall gallery.

Not sure about @ocefpaf's comments though. Maybe the concept is applicable without the Pangeo cloud stuff?

**Comment by ocefpaf** [comment]
In theory we could but in practice we have a hard time getting RAs to contribute to this one, or even the DMAC seminars, I'm not sure they'll maintain their own gallery.

**Comment by MathewBiddle** [comment]
Yeah. I wonder if this would be more enticing though? I do see some RAs with notebook repos already:

- https://github.com/SECOORA/data_challenge_2020
- https://github.com/CeNCOOS/notebooks

**Comment by ocefpaf** [comment]
The Data Challenge ones are probably not OK for an example gallery but the CeNCOOS ones seems to be.

**Comment by ocefpaf** [comment]
We moved to the JupyterBook format. Closing this.
