### ISSUE TITLE
Update 2018-02-27-pocean-timeSeries-demo to include attribution information

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/notebooks_demos#366]
Per a recent discussion concerning attribution, we can update the [pocean timeSeries demo](https://github.com/ioos/notebooks_demos/blob/master/notebooks/2018-02-27-pocean-timeSeries-demo.ipynb) to include an attribution step.

From the discussion:
> Organization W collected the oceanographic data data;
> Organization X received the data from Organization W and published it;
> Organization Y downloaded the data from Organization X and QC'd the datasets
> Organization  Z took the QC's data from Organization Y and generated netCDF for publication
> Organization G reviewed and uploaded the data to its ERDDAP for wider distribution.
> 
> Question 1: Who is the data creator? 
> 
> Question 2: Will acknowledging the chain of custody in the global attribute "Summary" sufficient?

https://ioos.github.io/notebooks_demos/notebooks/2018-02-27-pocean-timeSeries-demo/

We could create a new notebook as well. Thanks for the idea @ocefpaf!

**Comment by ocefpaf** [comment]
For future reference (copied from the ioos_tech thread):

```
creator_name: First Last
creator_email: firstlast@gmail.com
creator_url: http://www.myorg.org/
creator_type: person
creator_institution: My Institution
institution: Usually the sama as the above
publisher_name: RA Data Manager
publisher_email: ra@gmail.com
publisher_url: http://www.ra.org/
publisher_type: position
publisher_institution: The RA
program: List of Programs
project: List of projects
contributor_name: List of names
contributor_role: Principal Investigator, Field Program Manager, Data Manager, Quality Assessment
history: File generated my-awesome-script.py
```

See: https://data.nodc.noaa.gov/thredds/dodsC/ioos/nanoos/ohsucmop/woody/woody.240.A.CTD/200911-926.nc.html

**Comment by MathewBiddle** [comment]
moved to code lab. closing.
