### ISSUE TITLE
Binder to launch interactive RStudio session

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/notebooks_demos#367]
@bbest mentioned this at one point. I hope that's the right github handle!

See https://github.com/binder-examples/r

Not sure what to put in it yet, but we can cross that bridge once we figure out if it's something to add.

**Comment by emiliom** [comment]
I don't know if anything can be adapted from OceanHackWeek 2020, but we had RStudio deployed on our JupyterHub with conda. Our constraints and scope was different (we wanted to ensure it worked from the common Python & R conda environment), but still, there may be something of value there. @ocefpaf would have more specifics.

**Comment by ocefpaf** [comment]
@MathewBiddle we have a prototype for a Dockerfile that will bring RStudio. I'm also in touch with some folks that works at RStudio to guide us in the best practices to do this on binder. More on this soon...

**Comment by MathewBiddle** [comment]
I wonder if this will help me dynamically add time-series plots in a map popup, as I'm trying to do with https://github.com/ioos/notebooks_demos/pull/370.

**Comment by ocefpaf** [comment]
> I wonder if this will help me dynamically add time-series plots in a map popup, as I'm trying to do with #370.

Probably not. For that we would need a live kernel. The [thebe](https://github.com/executablebooks/thebe) is one way to do it, not sure how hard it is to implement.

**Comment by ocefpaf** [comment]
@MathewBiddle we never got the Dockerfile to work properly on binder. I don't think it is worth investing on this at the moment. We would require a live custom JupyterHub to support all that and this is beyond the scope of the site.
