### ISSUE TITLE
Using R to work with netCDF files

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/notebooks_demos#368]
- [x] What is language(s) for used in the example?
R
- [X] Is it focused on a particular module/software or an IOOS data service?
netCDF
- [X] Can you provide a minimum example of the expected code and results in a notebook?
https://ropensci.org/blog/2019/11/05/tidync/

Please provide a detailed description of the suggested example below:
I saw the blog post above and thought it would be a useful resource to have available to people. We could either add a new notebook exemplifying working with netCDF data using the IOOS Profile, or simply link to that example.

**Comment by ocefpaf** [comment]
> We could either add a new notebook exemplifying working with netCDF data using the IOOS Profile, or simply link to that example.

Let's do a new one and maybe mix it with a netCDF response from ERDDAP to make things interesting. I'll work on it this week.
