### ISSUE TITLE
New notebook announcement strategy 

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/notebooks_demos#385]
Other than monitoring this repository, how are people being notified that new notebooks are published?

**Comment by dpsnowden** [comment]
@MathewBiddle Good question.  There should be a communications plan associated with each new publication.  Speak to Kate but IMO it should include a write up in bi-weekly, EOTO, ioos_tech@googlegroup, ioos.ra.dmac, Twitter/FB plus whatever other channels you have access to and think appropriate.  We have access to those comms pathways now.  If you have suggestions for adding to that list please propose them.

**Comment by MathewBiddle** [comment]
@ocefpaf, is there some mechanism (GH actions?) that we can add to enforce a communication plan for each notebook release?

My thoughts:
* When a **new** notebook is merged a ticket gets created and assigned to whoever is in charge of communications (me for now).
  * The ticket has check boxes for the various venues for which to make the announcement to.
* Add a new column to the [project board](https://github.com/orgs/ioos/projects/1) for notify community?

**Comment by ocefpaf** [comment]
> @ocefpaf, is there some mechanism (GH actions?) that we can add to enforce a communication plan for each notebook release?
> 
> My thoughts:
> 
> * When a **new** notebook is merged a ticket gets created and assigned to whoever is in charge of communications (me for now).

This is probably possible. There are a few GH action to open issues. Just not sure how to connect them to a PR merge when most of the uses cases is the other way around. (Close issues when merging.)

>   * The ticket has check boxes for the various venues for which to make the announcement to.

I guess that we can template that. We'll need to solve the opening issue problem first.

> * Add a new column to the [project board](https://github.com/orgs/ioos/projects/1) for notify community?

That is probably harder. I'm not aware of an API for projects. Googling about it did not help much.

**Comment by MathewBiddle** [comment]
I am sorry, the last bullet wasn't fully explained. What I meant was, should we simply create a new category on the project board with the title "Notify the community" or "Share broadly"?

That way, after the PR is closed we can move the associated ticket into that category as a reminder to do those things.

I am just trying to add a hook in somewhere as a reminder to communicate that we have new notebooks..

**Comment by MathewBiddle** [comment]
See https://github.com/ioos/notebooks_demos/wiki#announcing and https://github.com/orgs/ioos/projects/1#column-13186308 as an interim solution.

**Comment by MathewBiddle** [comment]
I think the documentation is sufficient for now. Until we can figure out an automated way to notify at least the project manager.
