### ISSUE TITLE
Demonstrate accessing and using HFR data

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/notebooks_demos#4]
You may have a script that does this already but if you point me to it I will start playing with it.

**Comment by ocefpaf** [comment]
We have two notebooks on the topic added in https://github.com/ioos/notebooks_demos/pull/18: `CC_NDBC_SIO_HFRdata.ipynb` and `SIPHON_NCSS_HFR_DataAccess_v2.ipynb`. The former is focused on `compliance-checker` and the latter demonstrates how to get HFRadar using siphon, but it is incomplete.

We still need to
- [ ] add more examples,
- [ ] and to finish  `SIPHON_NCSS_HFR_DataAccess_v2.ipynb`.

**Comment by jbosch-noaa** [comment]
Thank you for listing that out @ocefpaf. 

The compliance-checker one will need updating at some point as a more generic notebook (rather than a notebook pointing out flaws in our HFR THREDDS servers).  

I would like to build out the SIPHON notebook to have a plot or two of some data.  We should think of framing it around a science/practical use question.

**Comment by ocefpaf** [comment]
Thanks @jbosch-noaa I am working on `SIPHON_NCSS_HFR_DataAccess_v2.ipynb` now but I updated the list with your comments so I do not lose trackof them.

**Comment by ocefpaf** [comment]
> The compliance-checker one will need updating at some point as a more generic notebook (rather than a notebook pointing out flaws in our HFR THREDDS servers).

I am thinking about how to address this here. `compliance-checker` is designed to be a `CLI` tool and we already [faced a few limitations](https://github.com/ioos/compliance-checker/issues/290) b/c of that design. So maybe we should:

- demonstrate the CLI via direct calls in the notebook,
- and show passing and failing files examples.

**Comment by jbosch-noaa** [comment]
@ocefpaf  - Sorry I have been slow to get back to you on this.  I am preparing for an unrelated workshop next week.  I think that explaining/demonstrating how a CLI based tool like the compliance-checker would be helpful to our blog audience (beginner to intermediate tech savvy scientists) .

When I return from this workshop I will start a WordPress file for the Access Data part of our website that will link to the User Blog that we are developing.
