### ISSUE TITLE
CO-OPS SOS with python notebook

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/notebooks_demos#404]
@LindsayRAbrams mentioned there is another API for the CO-OPS SOS data in this notebook. Maybe we should update this notebook at some point?
https://ioos.github.io/notebooks_demos/notebooks/2016-10-12-fetching_data/

**Comment by ocefpaf** [comment]
That would be nice. Is the new API the ERDDAP server for this data? If so, even better.

**Comment by LindsayRAbrams** [comment]
Sorry for the delayed response, I wanted to check with others in CO-OPS first on which data source would be best. From discussions with IT, either our Data API or ERDDAP server would work, depending on what is more useful for your users.
More info on CO-OPS Data API: https://api.tidesandcurrents.noaa.gov/api/prod/
More info on CO-OPS ERDDAP: https://opendap.co-ops.nos.noaa.gov/erddap/index.html

Let me know what you both think! We are happy to help where we can.

**Comment by ocefpaf** [comment]
I guess a notebook with both APIs would be nice. I will start one that updates the `2016-10-12-fetching_data`.

**Comment by MathewBiddle** [comment]
@ocefpaf, did you ever start this effort? If not, lets move the ticket to https://github.com/ioos/ioos_code_lab and clean this out.

**Comment by ocefpaf** [comment]
> @ocefpaf, did you ever start this effort? If not, lets move the ticket to https://github.com/ioos/ioos_code_lab and clean this out.

Yep. Let's move it to the new repo.

**Comment by MathewBiddle** [comment]
moved to code lab. closing.
