### ISSUE TITLE
Get Google Analytics working on the JuyterBook format

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#407]
@lohithmunakala you can follow the [discussion here](https://github.com/ioos/notebooks_demos/issues/190). Not that we did not forward with the changes in the current theme b/c we would need to modify them to JupyterBook.

**Comment by lohithmunakala** [comment]
@ocefpaf could you confirm if the GA code is G-W7S16LPGS7? (from https://github.com/ioos/notebooks_demos/pull/402). We can add this to the .yaml file of the jupyterbook to track the site.

**Comment by ocefpaf** [comment]
> @ocefpaf could you confirm if the GA code is G-W7S16LPGS7? (from #402). We can add this to the .yaml file of the jupyterbook to track the site.

@MathewBiddle created it but I believe that is the correct one.

**Comment by lohithmunakala** [comment]
> > @ocefpaf could you confirm if the GA code is G-W7S16LPGS7? (from #402). We can add this to the .yaml file of the jupyterbook to track the site.
> 
> @MathewBiddle created it but I believe that is the correct one.

Okay I'll use that and see how I can add it. Thanks!

**Comment by MathewBiddle** [comment]
Yes, the GA code is `G-W7S16LPGS7`. If it makes a difference, this is a [Google Analytics 4 property](https://support.google.com/analytics/answer/10089681?hl=en&utm_id=ad).
