### ISSUE TITLE
Document how to deploy Jupyter{book} locally from this repo

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/notebooks_demos#412]
Once we have agreed to move forward with Jupyter{Book} we should document how to deploy it on your local machine. Might be a simple update to https://github.com/ioos/notebooks_demos/wiki/Deploying-demo-center-website-on-your-local-machine.

**Comment by MathewBiddle** [comment]
Pointing to [this](https://jupyterbook.org/basics/build.html) might be sufficient. However, I am having trouble building it.

**Comment by lohithmunakala** [comment]
To run this locally, we need to have the `content` folder relative to the `_config.yml` and `_toc.yml` files.

The steps are as follows:
1. Install jupyter-book.
     ```pip -U install jupyter-book```
2. Run the following to build locally. 
    ```jupyter-book build <name-of-the-book>```

**Comment by lohithmunakala** [comment]
> Pointing to [this](https://jupyterbook.org/basics/build.html) might be sufficient. However, I am having trouble building it.

Could you let me know what the issue is?

**Comment by lohithmunakala** [comment]
> Once we have agreed to move forward with Jupyter{Book} we should document how to deploy it on your local machine. Might be a simple update to https://github.com/ioos/notebooks_demos/wiki/Deploying-demo-center-website-on-your-local-machine.

I am making changes to that deploying-locally.md file but with reference to how the future repo would probably look like.

**Comment by lohithmunakala** [comment]
@MathewBiddle, I guess this should be fine for the Deploying-demo-center-website-on-your-local-machine.md. 

**Requirements:**
* Git: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
* Jupyter{Book}: https://jupyterbook.org/intro.html

**Installation:**
* pip install -U jupyter-book

1. Clone the [notebooks_demo](https://github.com/ioos/notebooks_demos) repository.

   ```git clone https://github.com/ioos/notebooks_demos.git```
1. Once you have cloned the repository, you have all the required notebooks cloned onto your system (in the jupyterbook/content folder). Run the following command to build the Jupyter{Book}. 
   ```jupyter-book build jupyterbook```

* The command should be run relative to the jupyterbook folder

3. Click on the link that has been generated to view the website.

**Comment by MathewBiddle** [comment]
Fixed my problems by updating jupyter-book. I'll add this to the wiki once #409 is merged.

**Comment by MathewBiddle** [comment]
See https://github.com/ioos/notebooks_demos/wiki/Build-JupyterBook-locally

**Comment by lohithmunakala** [comment]
Seems cool! 

Could we add that the jupyerbook can also be built using `juyter-book build .` when you're inside the jupyerbook folder?

**Comment by MathewBiddle** [comment]
https://github.com/ioos/notebooks_demos/wiki/Build-JupyterBook-locally/_edit#build-the-jupyterbook

How's that?

**Comment by lohithmunakala** [comment]
Super cool!
