### ISSUE TITLE
New name for the IOOS Data Demo Center

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/notebooks_demos#413]
@mwengren @kbailey-noaa @ocefpaf 

Time to get creative! :)

I know we've discussed a rename to "Notebook Gallery". But, now we are moving towards using [Jupyter{book}](https://jupyterbook.org/intro.html) as the wrapper around the notebooks. So, I'm not sure if "Notebook Gallery" is still appropriate with that technology.

Looking through the Jupyter{book} [gallery of books](https://executablebooks.org/en/latest/gallery.html) the titles are slightly more descriptive. 

A couple of (not creative) thoughts: 
* "IOOS tools for ocean observations"
* "IOOS code suite"
* "Ocean observing system notebooks"

At a minimum, we can pick one of "Notebook Gallery" or "IOOS Data Demo Center" but we need to be consistent in our text. I see various names listed throughout [the site](https://ioos.github.io/notebooks_demos/) now.

**Comment by mwengren** [comment]
'IOOS Code Lab', 'IOOS CodeLab', 'IOOS Code Gallery'?  If we want to get away from the Notebook term.

You could also go with  Data Lab DataLab instead I suppose.  I'd vote against 'IOOS Code & Data Lab' just because that is too cumbersome.  

Just a few ideas.

**Comment by ocefpaf** [comment]
I like `IOOS Code Lab`.

**Comment by MathewBiddle** [comment]
I like `IOOS CodeLab` . When you [search for "codelab"](https://www.google.com/search?q=codelab&client=firefox-b-1-d&sxsrf=ALeKk02I6HfH3JPORvyocYB0skbobH5vOg%3A1624986239533&ei=f1LbYKmDINTS5NoPyqmt2AY&oq=codelab&gs_lcp=Cgdnd3Mtd2l6EAMyCggAELEDEIMBEEMyAggAMgYIABAHEB4yAggAMgYIABAHEB4yAggAMgIIADICCAAyAggAMgIIADoHCAAQRxCwAzoHCAAQsAMQQ0oECEEYAFD5pwRY-acEYJKrBGgBcAJ4AIABZ4gBwwGSAQMxLjGYAQCgAQGqAQdnd3Mtd2l6yAEKwAEB&sclient=gws-wiz&ved=0ahUKEwjpvsm8qb3xAhVUKVkFHcpUC2sQ4dUDCA4&uact=5) a few similar sites come up.

**Comment by MathewBiddle** [comment]
Once new name is decided should we change the repo name too?

**Comment by MathewBiddle** [comment]
Also, should update tile on https://ioos.us/

**Comment by MathewBiddle** [comment]
Okay `IOOS Code Lab` it is. 

Repo new name should be `ioos/code_lab` or `ioos/ioos_code_lab`?

**Comment by mwengren** [comment]
My vote would be to be more explicit: ioos_code_lab.

**Comment by MathewBiddle** [comment]
One hiccup is in the Google Analytics part. If we change the url, I think we will need a new GA id...

**Comment by ocefpaf** [comment]
> One hiccup is in the Google Analytics part. If we change the url, I think we will need a new GA id...

We just added it so we are not really losing historic data, right?

**Comment by ocefpaf** [comment]
Steps to rename the site (after a quick chat with @MathewBiddle):

1. change it internally in the MD pages
2. change the config files, CI, and Google analytics
3. rename the repository (coordinate with the change in the CI)


Notes: let's wait until the end of GSoC for 3 and people won't need to change their forks after the name change b/c GitHub handles that.

**Comment by MathewBiddle** [comment]
We've started a new repo at https://github.com/ioos/ioos_code_lab.

**Comment by ocefpaf** [comment]
@MathewBiddle are we ok to close this one?

**Comment by MathewBiddle** [comment]
Yeah, just need to make a ticket for GA in the ioos_code_lab repo. Not sure if that's working correctly or not.

**Comment by ocefpaf** [comment]
> Yeah, just need to make a ticket for GA in the ioos_code_lab repo. Not sure if that's working correctly or not.

It is in there. Not sure it it is working. Can you check the dashboard?

**Comment by MathewBiddle** [comment]
dashboard showing no users. Think I need to update some configuration for GA. Doing some digging now.
