### ISSUE TITLE
Run in Binder link fails

### ISSUE THREAD

**Issue by mwengren** [ioos/notebooks_demos#414]
I tried using the Binder link in the README and it seems to time out or fail in the Step 6 `COPY CONDARC` command.

Is there a way to add a link to each notebook to run individually via Binder.  Just a guess that the README link including the full master branch is slowing things down or otherwise causing issues.

**Comment by MathewBiddle** [comment]
At the bottom of each notebook there is a link to run a live instance of each notebook.
![image](https://user-images.githubusercontent.com/8480023/123835137-2fb62800-d8d6-11eb-8bfa-def1877f0cdf.png)

**Comment by ocefpaf** [comment]
> Just a guess that the README link including the full master branch is slowing things down or otherwise causing issues.

It is an easy fix but probably not worth doing it at the moment b/c this will be handled by #409 automatically. Also, the individual links in each notebook seems to be working.

**Comment by mwengren** [comment]
Will the JupyterBook interface show the 'Run in Binder' more prominently than the current Jekyll template?

@MathewBiddle and I talked about this a little, but it would be nice to make the process to run a notebook more obvious/straightforward, and perhaps even faster as well if possible?

What if we look into [Planetary Computer](https://planetarycomputer.microsoft.com/) since it's under the MS umbrella like GitHub?  No idea if they support anything similar to BinderHub, but just a suggestion.

**Comment by ocefpaf** [comment]
> Will the JupyterBook interface show the 'Run in Binder' more prominently than the current Jekyll template?

It will look like this:

![Screenshot from 2021-06-29 15-46-02](https://user-images.githubusercontent.com/950575/123851219-50d84200-d8f1-11eb-8db4-168036fb2976.png)


> What if we look into [Planetary Computer](https://planetarycomputer.microsoft.com/) since it's under the MS umbrella like GitHub? No idea if they support anything similar to BinderHub, but just a suggestion.

My guess is that they do not provide that as a service but I'll ask around. (Some former AnacondaInc/Pangeo folks work on that project and may help us.)
