### ISSUE TITLE
Rename some notebooks after the move to JupyterBook

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#415]
Original issue raised by @mwengren in https://github.com/ioos/notebooks_demos/issues/411#issuecomment-870803927

---
We should consider renaming some notebooks either as part of the transition to JupyterBook or shortly afterward.  

For example, for some of the IOOS Catalog-related notebooks, I'd like to use the name 'IOOS Catalog' explicitly.  This comment is based on the notebook titles used in the existing Data Demo Center site (https://ioos.github.io/notebooks_demos/code_gallery/) where the Titles differ from the physical notebook names:

- How to Search the IOOS CSW catalog with Python tools (https://ioos.github.io/notebooks_demos/notebooks/2016-12-19-exploring_csw/) - change to 'Searching the IOOS Catalog CSW service in Python'
- Fetching Data from a CSW catalog with Python tools (https://ioos.github.io/notebooks_demos/notebooks/2017-12-15-finding_HFRadar_currents/) - change to 'Fetching Data from the IOOS Catalog CSW service in Python'

Not sure if the existing titles will carry over directly to JupyterBook or not, but this would be a good opportunity to improve on those at the same time.  IOOS Catalog is just an example, we might want to make other changes as well.

**Comment by MathewBiddle** [comment]
As it stands the "page list" is a brutal list of text:
![image](https://user-images.githubusercontent.com/8480023/124799187-4685fb80-df22-11eb-9c7d-9049acb3c78f.png)

We should really think of some short names (1-4 words) that succinctly describe each page to use in that menu.

**Comment by MathewBiddle** [comment]
We've migrated to jupyterbook. Not sure if we need to simplify the text for the sidebar. Closing and will open in ioos_code_lab if it bugs me again.
