### ISSUE TITLE
Jupyter{Book} Enhacement

### ISSUE THREAD

**Issue by lohithmunakala** [ioos/notebooks_demos#417]
- [x] Add a standardized, centered IOOS header/masthead logo that links back to ioos.us
- [x] Make the IOOS image on the upper left point to ioos.us (we'll need to add the home link back into the menu probably)
- [x] footer: standardize to ioos.us design, add link to ioos.noaa.gov, contact info etc. Should have consistent look and feel if possible and match the content at the main ioos.us page

**Comment by lohithmunakala** [comment]
![Screenshot from 2021-07-07 01-05-08](https://user-images.githubusercontent.com/56470584/124656898-6b955280-debf-11eb-94f1-ac70f0cfa199.png)


@ocefpaf @MathewBiddle is this what we are looking at for the footer section? Links to respective social media handles and mail to webmaster.ioos.us@noaa.gov (given on the ioos.us website)? 

For the logo, should we change it or keep it the same? There isn't an option to link it back to ioos.us btw. I have added the link to ioos.us below in the footer section of the menu.

**Comment by MathewBiddle** [comment]
I guess it checks the boxes. 

The footer on ioos.us looks like this:
![image](https://user-images.githubusercontent.com/8480023/124661629-be4a1c80-de75-11eb-8471-a5b0c06b2d0e.png)
I don't think we will be able to replicate that fancy look through the JB.

@mwengren what do you think about the data demo center having the `Contact us` link go to webmaster?

I wonder if it would look better to make the logo larger? It just seems like a lot of text on that upper left portion.

Any other opinions are welcome.

**Comment by mwengren** [comment]
Hmm... that's a toss up.  All the ioos.us pages Contact Us footer links send email to webmaster.ioos.us@noaa.gov I think. 

But on our documentation pages at ioos.github.io, we also have a Feedback link at the top of the nav bar that sends email to data.ioos@noaa.gov.  

I'd say if this is the only contact email on the JupyterBook pages, we should use data.ioos@noaa.gov - will be more direct to someone in Ops for any feedback we get.

**Comment by MathewBiddle** [comment]
Agreed. Let's use data.ioos@noaa.gov. 

As for the logo, if you can increase the size that might be nice. Otherwise this looks good to me. 

Can we make the copyright look like ioos.us:
![image](https://user-images.githubusercontent.com/8480023/124798712-afb93f00-df21-11eb-847f-6732cbc9369c.png)

**Comment by lohithmunakala** [comment]
> Agreed. Let's use [data.ioos@noaa.gov](mailto:data.ioos@noaa.gov).
> 
> As for the logo, if you can increase the size that might be nice. Otherwise this looks good to me.
> 

The size of the logo depends on the size of the actual image as there is no option to modify it. A larger sized image would suffice. 

> Can we make the copyright look like ioos.us:
> ![image](https://user-images.githubusercontent.com/8480023/124798712-afb93f00-df21-11eb-847f-6732cbc9369c.png)

Okay will do this.

**Comment by lohithmunakala** [comment]
![image](https://user-images.githubusercontent.com/56470584/124809728-10766500-df7e-11eb-81dd-c312c9febed2.png)

@MathewBiddle, Would this size of this logo be fine?

**Comment by MathewBiddle** [comment]
looks good to me.
