### ISSUE TITLE
Push new DOI at zenodo

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/notebooks_demos#418]
once Jupyter{book} migration is complete we should push a new release and update the [DOI at zenodo](https://zenodo.org/record/293703#.YN9fEmhKhPY).

**Comment by ocefpaf** [comment]
Let's issue a new release 2.0 when the JB is ready to go.

**Comment by ocefpaf** [comment]
Done in https://github.com/ioos/ioos_code_lab/pull/1
