### ISSUE TITLE
Add more useful content in the README for the repo

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#421]
From @mwengren:

    At the moment, it's kind of light.
    Description of the overall project, developer build/run instructions (or link to them) and other things that
    are typical of project READMEs to better inspire potential users of it.

**Comment by ocefpaf** [comment]
> At the moment, it's kind of light.

At the new page we have a link to the page, new issues, the binder link, and how to cite it.

> Description of the overall project

It would be nice to have a better description. @MathewBiddle is that something you want to do? Maybe we already have it somewhere...

> developer build/run instructions (or link to them) and other things that
are typical of project READMEs to better inspire potential users of it.

This site is not Software so I'm not sure we need those. With that said, we do have information in the site on how to install miniconda and configure the IOOS environment.

**Comment by MathewBiddle** [comment]
Should be satisfied with https://github.com/ioos/ioos_code_lab/pull/21
