### ISSUE TITLE
Page organization

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/notebooks_demos#422]
I'm thinking back to the organization of these pages and how they don't really relate to one another. A user could go from Fetching data from CO-OPS SOS w/ python to plotting glider data. What's the connection there? 

This leads me to think that the next page feature doesn't really make sense.
![image](https://user-images.githubusercontent.com/8480023/124799674-cf9d3280-df22-11eb-8d05-0a66c7a2c3b8.png)

We might need to rethink the toc structure to put similar notebooks together (not just chapters, but within chapters). Like the erddapy notebook would go before the IOOS sensor map notebook, since it provides the building block of erddapy.

**Comment by MathewBiddle** [comment]
For example, the "Installing the IOOS Conda Environment" should be the first page you get directed to after the intro page.

**Comment by lohithmunakala** [comment]
I did some research and apparently, the Prev and the Next can't be removed. 

Reordering according to requirement makes sense. Could make that change.

**Comment by lohithmunakala** [comment]
TBH, I arranged it based on how it was back on the original site. We could make changes to the `_toc.yml` file.

**Comment by MathewBiddle** [comment]
Gotcha. That was the right way to do it initially. Now I think we have an opportunity to evaluate how these pages are presented to a user. We'll need to think about this some more and make adjustments as necessary.

**Comment by ocefpaf** [comment]
@MathewBiddle we moved a few things but to organize it better it will take someone to "read" the new site and open a new issue that we can track. I'm doing that at the moment but to fix bed renderings. If I find something that should be in a different category I'll open a new issue. For now, I think we can close this one.
