### ISSUE TITLE
Cleanup notebooks and resubmit draft PRs

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/notebooks_demos#425]
There are a few notebooks that were in development before we migrated. This ticket is to remind us to clean up the outstanding notebooks and make new PRs. See [here](https://github.com/ioos/notebooks_demos/pulls?q=is%3Apr+is%3Aopen+is%3Adraft).

Some of the formatting is wonky when migrated to JupyterBook (see below). We should:
1. [build JupyterBook locally](https://github.com/ioos/notebooks_demos/wiki/Build-JupyterBook-locally)
2. review each notebook for formatting errors
3. fix any issues and submit PR

![image](https://user-images.githubusercontent.com/8480023/125316336-08178480-e306-11eb-896f-f0a15060e147.png)

**Comment by lohithmunakala** [comment]
I just checked this, because JupyterBook follows the Markdown style for comments, the comment on the cell originally were in the "###" heading format. JupyterBook considers this as a heading and makes the size bigger. We can change this heading size.

**Comment by ocefpaf** [comment]
JB is correct here and the "right" fix should be in the notebook itself. We need to review those one by one :-(

**Comment by MathewBiddle** [comment]
@ocefpaf should we start cleaning up these draft notebook PR's?

**Comment by ocefpaf** [comment]
> @ocefpaf should we start cleaning up these draft notebook PR's?

The new site is up at https://github.com/ioos/ioos_code_lab, we should "copy" the notebooks from the PRs here and open new ones there. I'll add a list of task in the new repo for this. Let's close this one and work there: https://github.com/ioos/ioos_code_lab/issues/4
