### ISSUE TITLE
Create a notebook template for potential contributors

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/notebooks_demos#426]
I ran across EarthCube's [notebook template](https://github.com/earthcube/NotebookTemplates) a couple months ago and would like to discuss the potential to include something similar here.

**Comment by MathewBiddle** [comment]
Should also look at AGU's recommendations: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007007

**Comment by ocefpaf** [comment]
@MathewBiddle we discussed this briefly in our meetings but I have to confess I do not recall the final decision. Our notebooks are not really stand-alone and non-reproducible to require a template to ensure they run. That is b/c we provide an environment and we test-run them.

We only require a Title and some notebooks have an author listed, most do not. Maybe all we need is to standardize that? And both are usually checked in a PR review.

**Comment by MathewBiddle** [comment]
I don't think a template is necessary. However, I think it would be helpful to have a skeleton notebook for R and for Python. Each one would already be configured to use the appropriate kernel so a contributor could just copy and run from there. 

If you agree @ocefpaf, lets close this and start a new PR in ioos_code_lab.

**Comment by ocefpaf** [comment]
Copying a notebook with a defined kernel is not recommended b/c kernel names and version changes. Users may be confused by the "missing kernel choose one" message.

**Comment by ocefpaf** [comment]
Let's close this and move the discussion to the lab repo.
