### ISSUE TITLE
Refresh image on landing page?

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/notebooks_demos#427]
Since we are doing a full refresh, why not take a look at redoing the image:
![image](https://github.com/ioos/notebooks_demos/raw/master/jupyterbook/images/Data_Demo_Center_middlepic_size770.png)

**Comment by MathewBiddle** [comment]
Maybe use (with permission) one of the images in https://ian.umces.edu/media-library/?search=&media_album=&media_type=graphic&vector_or_raster=&sort_order=-date&filter=Apply+Filters

**Comment by ocefpaf** [comment]
It would be nice to get a refresh but... "Not it!" I'm terrible at visual stuff.
@lohithmunakala do you want to take a stab at this?

**Comment by MathewBiddle** [comment]
Thinking something more along the style of this:
![ioos_CodeLab_image](https://user-images.githubusercontent.com/8480023/127210871-bbce646c-5098-4f70-a337-948ab3e296e4.png)

**Comment by MathewBiddle** [comment]
![ioos_CodeLab_image_curved](https://user-images.githubusercontent.com/8480023/127212913-3335b054-410e-4ebf-8cff-be9fb83a5903.png)

**Comment by MathewBiddle** [comment]
Or, go with a hex cutout 😄 
![ioos_CodeLab_image_hex](https://user-images.githubusercontent.com/8480023/127214911-c51fb3f5-8e62-46c7-99f5-b8fe7846565b.png)

**Comment by mwengren** [comment]
Ooh, I like those!   Either the rounded corners, or the hex cutout, all look pretty good.  How did you make those Matt?  The hex version is cool but it shows fewer plots, unfortunately.

**Comment by ocefpaf** [comment]
I like the hex cuts but it would look better if they are each their own figure in a panel. I also like the round edges one but the images are giving me a "west coast all the way down" vibe ;-p

**Comment by lohithmunakala** [comment]
> It would be nice to get a refresh but... "Not it!" I'm terrible at visual stuff.
> @lohithmunakala do you want to take a stab at this?

The ones @MathewBiddle did look really cool. The round edges especially. Would be best for the JupyterBook.

**Comment by MathewBiddle** [comment]
Good catch @ocefpaf! Those are just some of the figures I pulled from the notebooks, with no intention from my cali background. I'll look around to make a more inclusive smattering of figs.

@mwengren 🤫 I used google slides and the crop feature 🤫

**Comment by MathewBiddle** [comment]
Now I'm just having fun with it. 
![ioos_CodeLab_image_multi_hex](https://user-images.githubusercontent.com/8480023/127250207-fa7844ab-41b9-466b-9541-48fac25d1f9f.png)

**Comment by MathewBiddle** [comment]
Let me know which one you all like and we can clean it up before we push the new site.

**Comment by MathewBiddle** [comment]
I tried to put the hex's in and I'm having trouble w/ the transparent background:
![image](https://user-images.githubusercontent.com/8480023/127557827-b180494e-33db-457f-bb7f-a23b50e3fe31.png)

**Comment by MathewBiddle** [comment]
got it
![image](https://user-images.githubusercontent.com/8480023/127560756-651f18b1-1b37-4012-8a08-d5ea092b8af5.png)

**Comment by lohithmunakala** [comment]
This honeycomb structure is the best 🔥

**Comment by MathewBiddle** [comment]
honeycomb!! I kept calling it 'multi-hex' 🤦

**Comment by ocefpaf** [comment]
We should put that in the code sprint t-shirt!
