### ISSUE TITLE
create contributing guidance

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/notebooks_demos#428]
Related to #426, but we should create CONTRIBUTING.md to help guide folks how to contribute.

**Comment by MathewBiddle** [comment]
woops, looks like I put that in the [wiki](https://github.com/ioos/notebooks_demos/wiki). What's better?

**Comment by lohithmunakala** [comment]
Keeping it inside the website itself might be better as per my opinion.

**Comment by ocefpaf** [comment]
> Keeping it inside the website itself might be better as per my opinion.

+1 to both actually. The website is markdown and there is no reason why not using the same file as the GiHub "standard" `CONTRIBUTING.md` and a page in the live site.

**Comment by lohithmunakala** [comment]
If we add this to the website, which chapter should I add it to?

**Comment by MathewBiddle** [comment]
Add another chapter under `OTHER RESOURCES` for `Contribute to IOOS CodeLab`.

**Comment by MathewBiddle** [comment]
fixed with https://github.com/ioos/ioos_code_lab/pull/20
