### ISSUE TITLE
Redirects or notification of site move

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/notebooks_demos#432]
The old url (https://ioos.github.io/notebooks_demos/code_gallery/) is still showing up in Google searches: https://www.google.com/search?q=ioos+code+gallery.

Anyway we can mitigate broken bookmarks at this point? Or, do we need to wait until the entire site is migrated to the new repo/url?

**Comment by MathewBiddle** [comment]
Looks like these are fixed! 🚀

**Comment by MathewBiddle** [comment]
shoot, looks like google is finding the site still hosted from this repo. Example: https://ioos.github.io/notebooks_demos/content/Code%20Gallery/data_analysis_and_visualization_notebooks/2018-12-04-grids.html

how can we forward to ioos_code_lab?

**Comment by ocefpaf** [comment]
> how can we forward to ioos_code_lab?

Hmm. Adding forwards to all subpages is hard. I'll see what I can do. However, Google will still find it for a while and then page ranks will drop. It is a problem that will "solve itself" soon.

**Comment by MathewBiddle** [comment]
Looks like this is solving itself. closing.
