### ISSUE TITLE
Complete migration to CodeLab

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/notebooks_demos#442]
Now that the CodeLab migration is complete, we should clean up this repo. A few tasks I see here:

- [ ] Update README to point folks to the [CodeLab](https://github.com/ioos/ioos_code_lab).
- [ ] Remove links to notebooks_demos website.
- [ ] Clean out the [wiki](https://github.com/ioos/notebooks_demos/wiki)
- [ ] Do we want to 'archive' this repo?
- [ ] Anything else?

**Comment by ocefpaf** [comment]
I prefer to just archive it as-is which in a way "cover" all the other bullet points b/c removes it from searches and, if folks have direct links to get here, they'll get a GH warning about its archival. What do you think?

**Comment by MathewBiddle** [comment]
works for me. I've moved all the tickets over too.

**Comment by ocefpaf** [comment]
Awesome! I'll add a note in the README first and archive it.
