### ISSUE TITLE
Get the HFR endpoints included in the ioos.us catalog

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/notebooks_demos#48]
In this [notebook](https://github.com/ioos/notebooks_demos/blob/master/notebooks/hfradar/finding_HFRadar_currents.ipynb) we don't find any current HFR data in the geoportal catalog because the metadata is [extra stale](http://www.ngdc.noaa.gov/geoportal/rest/document?id=%7B041E7399-5C99-4437-9A26-EC891C40AFF8%7D), and we don't find any curent HFR data in the ioos.us dev catalog because the metadata isn't there.   

I assume this is because geoportal was directly harvesting from the thredds catalogs for HFR data, right? 

So @mwengren, if we want this enabled, is the protocol to bark up the tree of SCOOS so they can add it to their WAF, so their WAF can be gobbled up by the master WAF, and ingested nightly into the dev catalog?

**Comment by mwengren** [comment]
@rsignell-usgs we're working up to releasing the harvest registry - which will be the entry point for data to get into dev-catalog.ioos.us, but it's still in beta mode right now. 

To not put the chicken before the egg, the first step to make this happen is for SCCOOS to generate a WAF of current ISO metadata via ncISO and THREDDS (or other means as appropriate).  I am planning to reach out to the RAs on this in the very near future.  I'll include you on that email and if you are able to lend a hand at all with that process that would be great.  We are working on writing up some documentation with best practices for ncISO/THREDDS, but that is very preliminary so far.  We'd appreciate any contributions to that as well if you want to add to it.

**Comment by rsignell-usgs** [comment]
@mwengren, okay, thanks!  Looking forward to the harvest registry!

**Comment by ocefpaf** [comment]
Here is an updated run that shows this issue:

https://via.hypothes.is/http://nbviewer.jupyter.org/github/ocefpaf/notebooks_demos/blob/finding_HFRadar/notebooks/2016-11-20-finding_HFRadar_currents.ipynb

**Comment by ocefpaf** [comment]
Closing this so we can track it in #128
