### ISSUE TITLE
Simple CSW search example

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#51]
Add a notebook with a simple CSW query that can be easily adapted to any region.

**Comment by rsignell-usgs** [comment]
I'm not sure this qualifies for "simple", but would this be a good candidate?
http://nbviewer.jupyter.org/gist/rsignell-usgs/0ebf02e333bad7f760bf

**Comment by ocefpaf** [comment]
Better than the one I have in mind!

**Comment by rsignell-usgs** [comment]
Should I create a new folder called "csw_search_examples" or something?

**Comment by ocefpaf** [comment]
> Should I create a new folder called "csw_search_examples" or something?

If you want push that notebook yes please :grimacing:
