### ISSUE TITLE
No SOS service found in Boston Light Swim notebook

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#53]
Not sure what is going on there but we need to investigate why none of the 3 catalogs are returning any SOS URL service.

See https://github.com/ioos/notebooks_demos/blob/master/notebooks/boston_light_swim/latest/log.txt#L39-L52

**Comment by ocefpaf** [comment]
The NDGC is dangerously outdated and I am not sure if the WHOI catalog ever returned `sos_urls`. Either way we are using `pyoos` to get that data so this is not too important.

I will re-check this once the IOOS catalog is up and running after Dec 14th.

**Comment by rsignell-usgs** [comment]
If you add "OGC:SOS" to the list, you get a bunch of SOS endpoints.  I did this locally.

**Comment by ocefpaf** [comment]
Good to know. I will added that service string. We should really write some best practices on the service strings BTW!
