### ISSUE TITLE
get rid of index.ipynb?

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/notebooks_demos#67]
Do we really want index.ipynb?
Every time we add a notebook, we have to modify the index.ipynb, but if we delete it, folks can just walk the directory structure.

What do folks think?

**Comment by ocefpaf** [comment]
It helps with the binder navigation but maintaining it can be a burden. I am fine removing. )Even more so when I finally get the rendered versions on `gh-pages` working.)

**Comment by rsignell-usgs** [comment]
Cool, Let's remove
