### ISSUE TITLE
Few model outputs for default dates

### ISSUE THREAD

**Issue by jsignell** [ioos/notebooks_demos#71]
I just tried to run the example notebooks for the Boston Light Swim and I only got a couple model outputs in the result:

![image](https://cloud.githubusercontent.com/assets/4806877/18446915/6053837a-78f2-11e6-9323-9f247a42a0e3.png)

Perhaps the model results for the default dates are no longer available?

**Comment by rsignell-usgs** [comment]
Yes, the NECOFS model datasets on THREDDS only has the last 3 days and the next 3 days forecast.

@ocefpaf , we should  allow the user to specify relative time in the YAML file in addition to absolute time and then change the default to relative time with start= now-3 days, stop= now+3 days, okay?

**Comment by ocefpaf** [comment]
Makes sense to use `today` &plusmn; 3 as default, and let users change both the `dt=3` and the relative date (`today`). That way the default will always return the latest comparison (with `NECOFS`) while we do not prevent users from playing with the notebook and checking what happens if they try a past date.

I will implement that soon.

**Comment by rsignell-usgs** [comment]
We should not limit the relative start/stop to a fixed time.   For other regions/applications, more hindcast may be desirable (e.g  -7 days/+3 days)

**Comment by ocefpaf** [comment]
> We should not limit the relative start/stop to the same time period (e.g. -3/+3 days). For other regions/applications, more hindcast may be desirable (e.g -7 days/+3 days)

That level of detail can be handled by spelling out the stat and stop dates. I do not want to make this over complex. My idea is to:

- if `start` and `stop` are defined do nothing and assume the user knows what s/he is doing
- if they are undefined default to `today` &plusmn; 3
- if one or the other is define offset the other by &plusmn; 3

Makes sense?
