### ISSUE TITLE
Why isn't COAWST showing up in boston_light_swim?

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/notebooks_demos#8]
@ocefpaf, any idea why COAWST isn't showing up in the boston_light_swim notebook?
https://github.com/ioos/notebooks_demos/tree/master/notebooks/boston_light_swim

**Comment by ocefpaf** [comment]
> @ocefpaf, any idea why COAWST isn't showing up in the boston_light_swim notebook?

Looking into it...

**Comment by rsignell-usgs** [comment]
Any luck?

**Comment by ocefpaf** [comment]
Nope. Do you have any clue? Both catalogs are not returning COAWST. (I was able to find it with the SECOORA notebook earlier today. 1-week older and different regional though.)

**Comment by rsignell-usgs** [comment]
The ISO record is here:
http://geoport-dev.whoi.edu/thredds/iso/coawst_4/use/fmrc/coawst_4_use_best.ncd?catalog=http%3A%2F%2Fgeoport-dev.whoi.edu%2Fthredds%2Fcatalog%2Fcoawst_4%2Fuse%2Ffmrc%2Fcatalog.html&dataset=coawst_4%2Fuse%2Ffmrc%2Fcoawst_4_use_best.ncd
and the times seem to be up to date.

And I see `sea_water_potential_temperature`.    Strange.

**Comment by ocefpaf** [comment]
Indeed. That narrows it down to get csw filter then, right? I tried many times and never got more than 3 URLs.

**Comment by ocefpaf** [comment]
@rsignell-usgs I am having trouble reaching `binder` and my in-laws connection cannot handle the notebook. My findings were not promising though. I always got `HYCOM` back (from both catalogs) and sometime both `FVCOM` models from the whoi catalog only, that was intermittent and some re-runs failed to find them.

I know the presentation is tomorrow, but I am travelling back home this night and I will be back online only after 16:30 tomorrow. I will try again but I that will be too late...

**Comment by ocefpaf** [comment]
Decided to give it another go now and I found it. Just my luck... Now let me debug the rest...

**Comment by ocefpaf** [comment]
Silly me. I was running on the old repository and an old version! Here is a run without any modification using this repo:

![viva3](https://cloud.githubusercontent.com/assets/950575/16027623/cc943098-31ad-11e6-8093-61a430b68e95.png)
