### ISSUE TITLE
Front page for the notebooks posts

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#81]
I pushed a live page to my [`gh-pages` branch](https://github.com/ocefpaf/notebooks_demos/tree/gh-pages) that uses the Jekyll theme and [notebook template](https://github.com/ocefpaf/notebooks_demos/blob/gh-pages/jupyter-jekyll.tpl).

See https://ocefpaf.github.io/notebooks_demos/

As soon as I get a :+1: on that I will start a front page for the notebooks.

**Comment by rsignell-usgs** [comment]
It would be nice if it looked something like
http://unidata.github.io/notebook-gallery/
but perhaps with one line captions that describe briefly something about what the notebook does

**Comment by lukecampbell** [comment]
I WAS NOT AWARE THIS EXISTED. HOW DID I NOT KNOW!

**Comment by rsignell-usgs** [comment]
I didn't know either until 30 minutes ago (I'm sitting at Unidata in the twice-annual Users Committee Meeting).

**Comment by ocefpaf** [comment]
The beauty of this setup is its simplicity. It is only a front page with `nbviewer` page links. I looked into sphinx-gallery to do something similar but we are "theme constraint" here because the notebooks must look like IOOS pages.

We can probably have both but we need to settle on the theme first. Feedback is welcomed BTW :smile:

**Comment by rsignell-usgs** [comment]
We might link to this somewhere also:
https://unidata.github.io/unidata-python-workshop/

**Comment by ocefpaf** [comment]
@jbosch-noaa, @mwengren, @lukecampbell, and @rsignell-usgs what do you think about this version:

http://ocefpaf.github.io/notebooks_demos/

**Comment by lukecampbell** [comment]
I like it!

**Comment by jbosch-noaa** [comment]
So it's documented in this repo, here is another good blog from the Office of Coastal Management that we should look to for inspiration:  https://geozoneblog.wordpress.com/

**Comment by ocefpaf** [comment]
This is actually done. We have a front page that shows a gallery-like list for tha available notebooks.

See https://ioos.github.io/notebooks_demos/
