### ISSUE TITLE
Side Bar and Blog Search Box

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/notebooks_demos#83]
As per my conversation with @ocefpaf, the blog site should have a side bar list of blog categories (e.g. tags) as well as a Search Box for folks to look for a blog post on something specific.

I see categories (tags) like:  HFR, Gliders, Models, Buoys, THREDDS, ERDAPP ... etc 
This list can be organic as we develop blog posts.

**Comment by ocefpaf** [comment]
- [X] a side-bar (but not linked to tags) is possible with the theme an already implemented
- [ ] search box

**Comment by jbosch-noaa** [comment]
Perhaps we use the Collections feature in Jekyll to organize our video links?
https://jekyllrb.com/docs/collections/

**Comment by jbosch-noaa** [comment]
I played around with the sidebar in the navigation.yml file but I am struggling with github to open a pull request.  I uploaded it to my branch here: 
https://github.com/jbosch-noaa/notebooks_demos/commit/ef6182a2f37e660775e8e161960091ae0a6df64e

If it renders ok it might be a temporary alternative. Whatcha think @ocefpaf ?

**Comment by ocefpaf** [comment]
Looks good to me. I don't have a way to render it right now  (away from my
laptop that has jekyll).

**Comment by jbosch-noaa** [comment]
After speaking with Micah, I suspect this won't render the way I envisioned.  Please take a look at it.  If it looks funny, don't merge the pull request.  

The highlighting I was talking about in our GChat can be seen in Micah's catalog page : https://ioos.github.io/catalog/

At some point I would like for use to figure out how to put bullets in the sidebar.  I think that would make it easier to read.

**Comment by ocefpaf** [comment]
> The highlighting I was talking about in our GChat can be seen in Micah's catalog page : 

I can see the text getting slightly darker and the creation of an underline when I hover the mouse. If that is the highlight you are talking about we do have it already. If not I am lost.

> At some point I would like for use to figure out how to put bullets in the sidebar. I think that would make it easier to read.

I thought that the new sections were created so we could remove the side bar. I am guessing it right? See #147 for more on this.

**Comment by jbosch-noaa** [comment]
We should start marking our notebooks and our posts as "collections" - you  might be doing this already.

 I think it would be good to have "collections" in the sidebar.  Right now it may seem repetitive but as we get more notebooks and videos it will make more sense.  So in addition to the Other Resources section of the sidebar, we should add:

Python Notebooks
External Notebooks
IOOS Video Tutorials
External Video Tutorials

Eventually we will have R Notebooks and Matlab Notebooks as different collections as well. Right now, the Python Notebook section would link to the Code Gallery. The External Notebook section would like to either a separate new page of links or other notebooks or blogs.

Both video tutorial headings would currently link to the Video Tutorial page.

**Comment by jbosch-noaa** [comment]
Most of this has been resolved.  Opening a new issue   #164  for the search box.
