### ISSUE TITLE
Merge multi-parts notebooks?

### ISSUE THREAD

**Issue by ocefpaf** [ioos/notebooks_demos#86]
@rsignell-usgs and @jbosch-noaa now that we are close to launch the webpage I have a question. Should we merge the multi-part notebooks into a single post, like the Boston Light Swim example, are should we post each part separately?

**Comment by rsignell-usgs** [comment]
I vote for multi-part notebooks as a single post.

**Comment by ocefpaf** [comment]
> I vote for multi-part notebooks as a single post.

That means merging the notebooks into a single one BTW. (I just noted I was not clear before.)

**Comment by jbosch-noaa** [comment]
Multi-part is ok provided we have very, very good commenting in language that a novice to intermediate user can understand.  One notebook with too many parts can become confusing, though.

I like the Boston Light Swim example when it is surrounded by a good user story on the application of the data and subsequent analysis. We could do the posts like they are episodes in a story that evolves .. that might make for an interesting read :P

**Comment by rsignell-usgs** [comment]
Hmmm.... we don't yet have the ability to run just a certain section of cells, right?

**Comment by ocefpaf** [comment]
> Hmmm.... we don't yet have the ability to run just a certain section of cells, right?

You mean render as HTML instead of run? No but that is probably possible. Although, even though advanced users might be tempted to suppress a few cells, I prefer a full explicit notebook. I find it easier to explain to others what is going on there when the whole code is present.

**Comment by rsignell-usgs** [comment]
I meant that the reason we split the notebook into 3 parts was to allow users to run notebook 2 independently to play with metrics, or notebook 3 to play with visualization, and to do either one without running notebook 1 again (the data loading part, which takes a long time).  

We could merge these all into one notebook with the same functionality if we had the ability to just run a range of cells (start running in a certain cell, and stop running in another cell).  But I don't think we have that capability.  We can run a single cell, or we can run all cells before or after.

**Comment by ocefpaf** [comment]
Got it. But now that I think of it, even though I do not the idea of forking, we should really host the muitl-part in a different folder and create a unified version for the post. That is because the post will be static once created, while the multi-part version will be constantly updated.

**Comment by rsignell-usgs** [comment]
Ah, okay, good thinking.   I'm fine with that!

**Comment by jbosch-noaa** [comment]
I like that idea too. :)

**Comment by ocefpaf** [comment]
Merged them into one in https://github.com/ioos/notebooks_demos/pull/130
Note that the original ones will reaming in staged notebooks.

**Comment by ocefpaf** [comment]
This task is complete as soon as we merge #130.
