### ISSUE TITLE
Matlab, R & Octave converted notebooks

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/notebooks_demos#87]
I wanted to make sure the email conversation from the "Tech blog" email thread is captured here:

@dpsnowden wrote:   Thanks Filipe.  It looks good.  I also agree with not introducing Wordpress and a manual option for updating.
        But, your automated procedure assumes that the source for a blog post is some form of Jupyter notebook which covers Python, R, and a few other languages.  What is your recommendation if someone wants to submit a Matlab script or some other language that isn't easily rendered as HTML?  Can that still be done in the github.io framework?

@ocefpaf wrote:    Regardless of the language we will be able to convert to HTML. We may not be able to run it at the test phase though. I will add to simple examples just to test the syntax highlight.

I added a R, Matlab and Octave example to the test page: http://ocefpaf.github.io/notebooks_demos/ 

You will note that the syntax highlight worked for matlab and R. No idea why octave failed there. Unfortunately the colors used for the highlight are Python biased due to a limitation in the nbconverter parser but I am already working with the Jpuyter group to get that working.

So converting another Jupyter notebook to HTML is not a problem. The problem will be certifying its correctness with Travis-CI as matlab is not available there.
-Filipe

PS: there is a bug in the gallery where all the boxes are squished in a single row. I am looking into it...

**Comment by jbosch-noaa** [comment]
Filipe - These examples are good.  I noticed that the second Matlab figure on ln [2] though is also squished.

**Comment by ocefpaf** [comment]
> @ocefpaf - These examples are good. I noticed that the second Matlab figure on ln [2] though is also squished.

That is just the bad automatic figure styling on the `Matlab` side :smile: we can tweak the figure and make it is "busy."

Those example are not meant to be in the final version. I created only to check the syntax highlight. We can work some nicer muilt-languages example later though.

**Comment by ocefpaf** [comment]
We broken this issue into smaller parts that we either already addressed or will be address soon. Closing this. Please re-open if I am wrong.
