### ISSUE TITLE
Demonstrate access and usage of glider data

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/notebooks_demos#9]
We should create a notebook demonstrating how to access and use glider data from the Gilder DAC.  We should demo plotting:

- [ ] A glider track overlay on a map- Dimension: space - Lat/Lon
- [ ] Glider profile data at one or more Lat/Lon locations: Dimension: depth at one location
- [ ] A in-water cross-section of glider data (temperature or salinity) along a glider track. Dimension: Depth and Space (Glider track)

**Comment by ocefpaf** [comment]
Done in #60 and #61
