### ISSUE TITLE
IOOS Catalog (CWS) Search Example notebook

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/notebooks_demos#94]
@ocefpaf  - I like the idea of this [notebook](https://github.com/ioos/notebooks_demos/blob/master/notebooks/csw_search_example.ipynb) on searching a CSW.  With a few more comments I think it would be a good one to post relatively soon.  I would like to time the post to the release of the new IOOS Catalog.  This way we can use that CSW instead of the NOAA catalog and we can drum up new users.

I'm sure @mwengren would be a good reviewer once we have it all written.

**Comment by rsignell-usgs** [comment]
Cool!   I'm still unsure which endpoint that notebook should be pointing to.  Is it 
`https://data.ioos.us/csw`, `ioos_dev='https://dev-catalog.ioos.us/csw`, or both?

**Comment by jbosch-noaa** [comment]
@rsignell-usgs - Once the IOOS Catalog is released, https://data.ioos.us/csw will be the link.  

Am I correct @mwengren ?

**Comment by mwengren** [comment]
Yes, for now it should be dev-catalog.ioos.us, but sometime in Nov (4 or
later) it will be data.ioos.us.

**Comment by ocefpaf** [comment]
> Yes, for now it should be dev-catalog.ioos.us, but sometime in Nov (4 or
later) it will be data.ioos.us.

https://dev-catalog.ioos.us/csw seems to be down again though:

![cat](https://cloud.githubusercontent.com/assets/950575/19559155/da62ee2e-96a4-11e6-9636-26cfc5fa36c9.png)

Cannot wait for  Nov 4th :wink:

**Comment by ocefpaf** [comment]
PR https://github.com/ioos/notebooks_demos/pull/128 addresses this issue.

**Comment by jbosch-noaa** [comment]
@ocefpaf  - I know we have been trying to debug #128  but what happened to working with this[ notebook](https://github.com/ioos/notebooks_demos/blob/master/notebooks/staged_noteooks/csw_search_example.ipynb)?  We can continue to work with Scripps and NDBC to improve their TDS but in the mean time I think we should post a more simple CSW example now that the new catalog is live.

**Comment by ocefpaf** [comment]
Done in https://github.com/ioos/notebooks_demos/pull/154 and we will have two more soon.
